<?php

namespace Database\Seeders;

use App\Models\CmsBuilderBlock;
use Illuminate\Database\Seeder;

class CmsBuilderBlockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blocks = [
            // ── Header Containers & Elements ──────────────────────────────────────
            [
                'id'                => 1,
                'title'             => 'Site Alerts | Sharing Icons',
                'target_element'    => 'top_sharing_container',
                'type'              => 1,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 0,
                'sort_tablet'       => 0,
                'sort_mobile'       => 5,
                'content_desktop'   => '',
                'content_tablet'    => '',
                'content_mobile'    => '',
                'is_active_desktop' => true,
                'is_active_tablet'  => false,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 2,
                'title'             => 'Top Navigation',
                'target_element'    => 'top_nav_container',
                'type'              => 1,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 8,
                'sort_tablet'       => 9,
                'sort_mobile'       => 0,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 3,
                'title'             => 'Header Row #1',
                'target_element'    => 'header_row1',
                'type'              => 1,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 10,
                'sort_tablet'       => 4,
                'sort_mobile'       => 9,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => false,
                'is_active_tablet'  => false,
                'is_active_mobile'  => false,
            ],
            [
                'id'                => 4,
                'title'             => 'Header Section',
                'target_element'    => 'site_header_container',
                'type'              => 1,
                'section_type'      => 'header',
                'is_placeholder'    => true,
                'sort_desktop'      => 4,
                'sort_tablet'       => 5,
                'sort_mobile'       => 1,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 5,
                'title'             => 'Header Row #2',
                'target_element'    => 'header_row2',
                'type'              => 1,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 9,
                'sort_tablet'       => 10,
                'sort_mobile'       => 10,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => false,
                'is_active_tablet'  => true,
                'is_active_mobile'  => false,
            ],
            [
                'id'                => 6,
                'title'             => 'Header - Logo Area',
                'target_element'    => 'header_logo',
                'type'              => 2,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 5,
                'sort_tablet'       => 6,
                'sort_mobile'       => 2,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 7,
                'title'             => 'Header Column #1',
                'target_element'    => 'header_col1',
                'type'              => 2,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 6,
                'sort_tablet'       => 7,
                'sort_mobile'       => 3,
                'content_desktop'   => null,
                'content_tablet'    => '[plugin:live-search-2026]',
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => false,
            ],
            [
                'id'                => 8,
                'title'             => 'Header Column #2',
                'target_element'    => 'header_col2',
                'type'              => 2,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 7,
                'sort_tablet'       => 8,
                'sort_mobile'       => 4,
                'content_desktop'   => '[plugin:live-search-2026]',
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => false,
                'is_active_mobile'  => false,
            ],
            [
                'id'                => 35,
                'title'             => 'Cart & Account Features',
                'target_element'    => 'header_features',
                'type'              => 2,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 8,
                'sort_tablet'       => 8,
                'sort_mobile'       => 8,
                'content_desktop'   => '{{Cart & User Account Icons}}',
                'content_tablet'    => '{{Cart & User Account Icons}}',
                'content_mobile'    => '{{Cart & User Account Icons}}',
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 36,
                'title'             => 'Header & Mobile Search Bar',
                'target_element'    => 'header_search',
                'type'              => 2,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 99,
                'sort_tablet'       => 99,
                'sort_mobile'       => 99,
                'content_desktop'   => '[plugin:live-search-2026]',
                'content_tablet'    => '[plugin:live-search-2026]',
                'content_mobile'    => '[plugin:live-search-2026]',
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 9,
                'title'             => 'Sharing Column #1',
                'target_element'    => 'sharing_col1',
                'type'              => 3,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 1,
                'sort_tablet'       => 1,
                'sort_mobile'       => 6,
                'content_desktop'   => '[plugin:newsflash-2026]',
                'content_tablet'    => '',
                'content_mobile'    => '{{Search Bar: Live Keyword Search}}',
                'is_active_desktop' => true,
                'is_active_tablet'  => false,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 10,
                'title'             => 'Sharing Column #2',
                'target_element'    => 'sharing_col2',
                'type'              => 3,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 2,
                'sort_tablet'       => 2,
                'sort_mobile'       => 7,
                'content_desktop'   => null,
                'content_tablet'    => '',
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => false,
                'is_active_mobile'  => false,
            ],
            [
                'id'                => 11,
                'title'             => 'Sharing Column #3',
                'target_element'    => 'sharing_col3',
                'type'              => 3,
                'section_type'      => 'header',
                'is_placeholder'    => false,
                'sort_desktop'      => 3,
                'sort_tablet'       => 3,
                'sort_mobile'       => 8,
                'content_desktop'   => '[plugin:social-icons-2026]',
                'content_tablet'    => '',
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => false,
                'is_active_mobile'  => false,
            ],

            // ── Footer Rows & Columns ─────────────────────────────────────────────
            [
                'id'                => 12,
                'title'             => 'Footer Row #1',
                'target_element'    => 'footer_row1',
                'type'              => 4,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 1,
                'sort_tablet'       => 1,
                'sort_mobile'       => 1,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 13,
                'title'             => 'Footer Row #2',
                'target_element'    => 'footer_row2',
                'type'              => 4,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 8,
                'sort_tablet'       => 8,
                'sort_mobile'       => 8,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => false,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 14,
                'title'             => 'Footer Row #3',
                'target_element'    => 'footer_row3',
                'type'              => 4,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 0,
                'sort_tablet'       => 0,
                'sort_mobile'       => 0,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => false,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 15,
                'title'             => 'Footer Columns - Primary',
                'target_element'    => 'site_footer_columns_primary',
                'type'              => 4,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 2,
                'sort_tablet'       => 2,
                'sort_mobile'       => 2,
                'content_desktop'   => null,
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 16,
                'title'             => 'Footer Primary Column #1',
                'target_element'    => 'footer_col1',
                'type'              => 5,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 3,
                'sort_tablet'       => 3,
                'sort_mobile'       => 3,
                'content_desktop'   => '<h3>Navigation</h3><ul class="space-y-2"><li><a href="/">Home</a></li><li><a href="/shop">Shop Catalog</a></li><li><a href="/shop?featured=1">Featured Products</a></li><li><a href="/brands">Our Brands</a></li><li><a href="/kb">Knowledge Base</a></li></ul>',
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 17,
                'title'             => 'Footer Primary Column #2',
                'target_element'    => 'footer_col2',
                'type'              => 5,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 4,
                'sort_tablet'       => 4,
                'sort_mobile'       => 4,
                'content_desktop'   => '<h3>Customer Service</h3><ul class="space-y-2"><li><a href="/cart">Shopping Cart</a></li><li><a href="/checkout">Checkout</a></li><li><a href="/orders">Order Status</a></li><li><a href="/shipping-policy">Shipping Policy</a></li><li><a href="/returns">Returns &amp; Exchanges</a></li></ul>',
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 18,
                'title'             => 'Footer Primary Column #3',
                'target_element'    => 'footer_col3',
                'type'              => 5,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 5,
                'sort_tablet'       => 5,
                'sort_mobile'       => 5,
                'content_desktop'   => '<h3>Company</h3><ul class="space-y-2"><li><a href="/about-us">About Us</a></li><li><a href="/contact">Contact Support</a></li><li><a href="/privacy-policy">Privacy Policy</a></li><li><a href="/terms">Terms of Service</a></li><li><a href="/faq">FAQ</a></li></ul>',
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 19,
                'title'             => 'Footer Primary Column #4',
                'target_element'    => 'footer_col4',
                'type'              => 5,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 6,
                'sort_tablet'       => 6,
                'sort_mobile'       => 6,
                'content_desktop'   => '<h3>Corporate Info</h3><div class="space-y-2 text-xs"><p class="font-semibold text-slate-200">Storefront Headquarters</p><p class="text-slate-400">100 Enterprise Parkway, Suite 400<br>Austin, TX 78701</p><p class="text-slate-300 pt-1"><strong>Phone:</strong> <a href="tel:18005550199">+1 (800) 555-0199</a></p><p class="text-slate-300"><strong>Email:</strong> <a href="mailto:support@store.com">support@store.com</a></p><p class="text-slate-400"><strong>Hours:</strong> Mon – Fri: 9am – 6pm EST</p></div>',
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 22,
                'title'             => 'Footer Primary Column #5',
                'target_element'    => 'footer_col5',
                'type'              => 5,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 7,
                'sort_tablet'       => 7,
                'sort_mobile'       => 7,
                'content_desktop'   => '<h3>Connect With Us</h3><p class="text-xs text-slate-400 mb-3 leading-relaxed">Follow our social channels for official updates, news flash announcements, and special promotions.</p><div>[plugin:social-icons-2026 align=left size=md font_awesome=on]</div>',
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
            [
                'id'                => 20,
                'title'             => 'Footer Row #4',
                'target_element'    => 'footer_row4',
                'type'              => 4,
                'section_type'      => 'footer',
                'is_placeholder'    => false,
                'sort_desktop'      => 9,
                'sort_tablet'       => 9,
                'sort_mobile'       => 9,
                'content_desktop'   => '<div class="w-full max-w-[var(--site-max-width)] mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 py-2 text-xs"><div>© {{year}} All Rights Reserved. Powered by Modern E-Commerce.</div><div class="flex items-center gap-4"><a href="/privacy-policy" class="hover:underline">Privacy Policy</a><span class="opacity-40">•</span><a href="/terms" class="hover:underline">Terms of Service</a><span class="opacity-40">•</span><div>[plugin:social-icons-2026 size=sm font_awesome=on]</div></div></div>',
                'content_tablet'    => null,
                'content_mobile'    => null,
                'is_active_desktop' => true,
                'is_active_tablet'  => true,
                'is_active_mobile'  => true,
            ],
        ];

        foreach ($blocks as $block) {
            CmsBuilderBlock::updateOrCreate(['id' => $block['id']], $block);
        }
    }
}
