<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds all hardcoded public-facing blade labels into site_labels.
 * Each entry: [label_key, section_id, language_id, file_name, label_description, label_default]
 * language_id 0 = default / English.
 */
class SiteLabelsSeeder extends Seeder
{
    public function run(): void
    {
        $now    = now();
        $labels = $this->labels();

        $chunks = array_chunk($labels, 50);
        foreach ($chunks as $chunk) {
            $rows = array_map(fn ($r) => [
                'label_key'         => $r[0],
                'section_id'        => $r[1],
                'file_name'         => $r[2],
                'label_description' => $r[3],
                'label_default'     => $r[4],
                'label_custom'      => null,
                'last_updated'      => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ], $chunk);

            DB::table('site_labels')->upsert(
                $rows,
                ['label_key'],
                ['label_description', 'label_default', 'file_name', 'section_id', 'updated_at']
            );
        }
    }

    // -------------------------------------------------------------------------
    // Label definitions
    // Format: [label_key, section_id, file_name, label_description, label_default]
    // -------------------------------------------------------------------------
    private function labels(): array
    {
        return [
            // ── Section 0: Global / Layout ─────────────────────────────────
            ['global.added_to_cart_heading',      0, 'public.blade.php',     'Cart confirmation modal heading',               'Added to Cart!'],
            ['global.added_to_cart_message',      0, 'public.blade.php',     'Cart confirmation modal body message',          'You have successfully added this item to your shopping cart.'],
            ['global.cart_modal_item_details',    0, 'public.blade.php',     'Cart modal item details label',                 'Item Details'],
            ['global.cart_modal_quantity',        0, 'public.blade.php',     'Cart modal quantity label',                     'Quantity:'],
            ['global.cart_modal_go_to_checkout',  0, 'public.blade.php',     'Cart modal go to checkout button',              'Go to Checkout'],
            ['global.cart_modal_continue_shopping',0,'public.blade.php',     'Cart modal continue shopping button',           'Continue Shopping'],
            ['global.error_modal_heading',        0, 'public.blade.php',     'Cart error modal heading',                      'Unable to Add to Cart'],
            ['global.error_modal_dismiss',        0, 'public.blade.php',     'Cart error modal dismiss button',               'Dismiss'],
            ['global.error_unexpected',           0, 'public.blade.php',     'Generic unexpected error message',              'An unexpected error occurred.'],
            ['global.sign_out',                   0, 'guest.blade.php',      'Sign out button',                               'Sign Out'],

            // ── Section 1: Navigation & Header ────────────────────────────
            ['nav.home',                          1, 'public-header.blade.php',       'Home navigation link',                 'Home'],
            ['nav.shop',                          1, 'public-header.blade.php',       'Shop navigation link',                 'Shop'],
            ['nav.knowledge_base',                1, 'public-header.blade.php',       'Knowledge Base navigation link',       'Knowledge Base'],
            ['nav.sign_in',                       1, 'public-header.blade.php',       'Sign in button/link',                  'Sign In'],
            ['nav.menu',                          1, 'public-header.blade.php',       'Mobile menu label',                    'Menu'],
            ['nav.cart',                          1, 'public-navigation.blade.php',   'Cart navigation link',                 'Cart'],
            ['nav.tickets',                       1, 'public-navigation.blade.php',   'Tickets navigation link',              'Tickets'],
            ['nav.orders',                        1, 'public-navigation.blade.php',   'Orders navigation link',               'Orders'],
            ['nav.downloads',                     1, 'public-navigation.blade.php',   'Downloads navigation link',            'Downloads'],
            ['nav.log_out',                       1, 'public-navigation.blade.php',   'Log out button',                       'Log Out'],
            ['nav.dashboard',                     1, 'public-navigation.blade.php',   'Dashboard navigation link',            'Dashboard'],
            ['nav.my_account',                    1, 'public-navigation.blade.php',   'My Account heading in nav',            'My Account'],
            ['nav.categories_fallback',           1, 'category-menu-widget.blade.php','Categories button fallback text',      'Categories'],
            ['nav.categories_empty',              1, 'category-menu-widget.blade.php','No categories found message',          'No categories found.'],
            ['nav.brands_fallback',               1, 'public-brands-menu.blade.php',  'Brands button fallback text',          'Brands'],
            ['nav.brands_empty',                  1, 'public-brands-menu.blade.php',  'No brands registered message',         'No brands registered.'],

            // ── Section 2: Footer ─────────────────────────────────────────
            ['footer.all_rights_reserved',        2, 'footer.blade.php',              'Footer copyright text',                'All rights reserved.'],
            ['footer.nav_home',                   2, 'footer.blade.php',              'Footer home link',                     'Home'],
            ['footer.nav_knowledge_base',         2, 'footer.blade.php',              'Footer knowledge base link',           'Knowledge Base'],
            ['footer.nav_dashboard',              2, 'footer.blade.php',              'Footer dashboard link',                'Dashboard'],
            ['footer.nav_sign_in',                2, 'footer.blade.php',              'Footer sign in link',                  'Sign In'],

            // ── Section 3: Shopping Cart ───────────────────────────────────
            ['cart.page_heading',                 3, 'shopping-cart.blade.php',       'Cart page main heading',               'Your Shopping Cart'],
            ['cart.empty_heading',                3, 'shopping-cart.blade.php',       'Empty cart heading',                   'Your cart is empty'],
            ['cart.empty_message',                3, 'shopping-cart.blade.php',       'Empty cart body message',              'Add products to your cart to see them here.'],
            ['cart.continue_shopping',            3, 'shopping-cart.blade.php',       'Continue shopping button',             'Continue Shopping'],
            ['cart.locked_bogo',                  3, 'shopping-cart.blade.php',       'BOGO locked item status',              'Locked (BOGO)'],
            ['cart.qty_max_limit',                3, 'shopping-cart.blade.php',       'Max quantity limit status',            'Qty: 1 (Max limit)'],
            ['cart.order_summary',                3, 'shopping-cart.blade.php',       'Order summary heading',                'Order Summary'],
            ['cart.subtotal',                     3, 'shopping-cart.blade.php',       'Subtotal label',                       'Subtotal'],
            ['cart.discount',                     3, 'shopping-cart.blade.php',       'Discount label',                       'Discount:'],
            ['cart.shipping',                     3, 'shopping-cart.blade.php',       'Shipping label',                       'Shipping'],
            ['cart.shipping_calculated',          3, 'shopping-cart.blade.php',       'Shipping calculated at checkout note', 'Calculated at checkout'],
            ['cart.total',                        3, 'shopping-cart.blade.php',       'Total label',                          'Total'],
            ['cart.proceed_to_checkout',          3, 'shopping-cart.blade.php',       'Proceed to checkout button',           'Proceed to Checkout'],
            ['cart.slide_heading',                3, 'slide-cart.blade.php',          'Slide cart panel heading',             'Shopping Cart'],
            ['cart.slide_empty_heading',          3, 'slide-cart.blade.php',          'Slide cart empty heading',             'Your cart is empty'],
            ['cart.slide_empty_message',          3, 'slide-cart.blade.php',          'Slide cart empty message',             'Add products to start shopping.'],
            ['cart.slide_each',                   3, 'slide-cart.blade.php',          'Per-unit price label in slide cart',   'each'],
            ['cart.slide_promos',                 3, 'slide-cart.blade.php',          'Promos/discounts label in slide cart', 'Promos / Discounts'],

            // ── Section 4: Checkout ────────────────────────────────────────
            ['checkout.page_heading',                   4, 'checkout.blade.php', 'Checkout page heading',                                         'Checkout'],
            ['checkout.returning_customer_heading',     4, 'checkout.blade.php', 'Returning customer panel heading',                              'Returning Customer?'],
            ['checkout.returning_customer_message',     4, 'checkout.blade.php', 'Returning customer body message',                               'Sign in to check out faster with your saved details, or continue below to order as a guest.'],
            ['checkout.sign_in_heading',                4, 'checkout.blade.php', 'Sign in panel heading',                                         'Sign In to Your Account'],
            ['checkout.sign_in_continue',               4, 'checkout.blade.php', 'Sign in and continue button',                                   'Sign In & Continue'],
            ['checkout.or_continue_with',               4, 'checkout.blade.php', 'Social login divider text',                                     'Or continue with'],
            ['checkout.shipping_details',               4, 'checkout.blade.php', 'Shipping details form heading',                                 'Shipping Details'],
            ['checkout.customer_info',                  4, 'checkout.blade.php', 'Customer info heading (digital-only orders)',                    'Customer Info'],
            ['checkout.field_full_name',                4, 'checkout.blade.php', 'Full name field label',                                         'Full Name'],
            ['checkout.field_email',                    4, 'checkout.blade.php', 'Email address field label',                                     'Email Address'],
            ['checkout.field_email_placeholder',        4, 'checkout.blade.php', 'Email address field placeholder',                               'you@example.com'],
            ['checkout.field_company',                  4, 'checkout.blade.php', 'Company field label',                                           'Company (Optional)'],
            ['checkout.field_address1',                 4, 'checkout.blade.php', 'Address line 1 field label',                                    'Address Line 1'],
            ['checkout.field_address2',                 4, 'checkout.blade.php', 'Address line 2 field label',                                    'Address Line 2 (Optional)'],
            ['checkout.field_city',                     4, 'checkout.blade.php', 'City field label',                                              'City'],
            ['checkout.field_postal',                   4, 'checkout.blade.php', 'Postal/ZIP field label',                                        'Postal / ZIP Code'],
            ['checkout.field_country',                  4, 'checkout.blade.php', 'Country field label',                                           'Country'],
            ['checkout.field_country_placeholder',      4, 'checkout.blade.php', 'Country select placeholder',                                    'Select Country'],
            ['checkout.field_state',                    4, 'checkout.blade.php', 'State field label',                                             'State'],
            ['checkout.field_state_placeholder',        4, 'checkout.blade.php', 'State select placeholder',                                     'Select State'],
            ['checkout.field_province',                 4, 'checkout.blade.php', 'Province/Territory field label',                                'Province / Territory'],
            ['checkout.field_province_placeholder',     4, 'checkout.blade.php', 'Province select placeholder',                                   'Select Province'],
            ['checkout.field_region',                   4, 'checkout.blade.php', 'Region field label (international)',                            'State / Region (Optional)'],
            ['checkout.field_region_placeholder',       4, 'checkout.blade.php', 'Region field placeholder',                                     'e.g. London'],
            ['checkout.field_password',                 4, 'checkout.blade.php', 'Password field label',                                          'Password'],
            ['checkout.field_password_optional',        4, 'checkout.blade.php', 'Optional password field label',                                 'Create a Password (Optional)'],
            ['checkout.field_password_optional_message',4, 'checkout.blade.php', 'Optional password helper message',                              'Provide a password if you want to register and speed through future purchases.'],
            ['checkout.field_confirm_password',         4, 'checkout.blade.php', 'Confirm password field label',                                  'Confirm Password'],
            ['checkout.select_placeholder',             4, 'checkout.blade.php', 'Generic select dropdown placeholder',                           '— Select —'],
            ['checkout.continue_to_review',             4, 'checkout.blade.php', 'Continue to review button',                                     'Continue to Review'],
            ['checkout.order_details',                  4, 'checkout.blade.php', 'Order details section heading',                                 'Order Details'],
            ['checkout.qty_label',                      4, 'checkout.blade.php', 'Quantity label',                                                'Qty:'],
            ['checkout.requires_shipping',              4, 'checkout.blade.php', 'Requires shipping badge',                                       'Requires Shipping'],
            ['checkout.digital_delivery',               4, 'checkout.blade.php', 'Digital delivery badge',                                        'Digital Delivery'],
            ['checkout.coupon_heading',                 4, 'checkout.blade.php', 'Coupon/promo section heading',                                  'Promo / Coupon Code'],
            ['checkout.coupon_active',                  4, 'checkout.blade.php', 'Active coupon label',                                           'Coupon Active:'],
            ['checkout.coupon_remove',                  4, 'checkout.blade.php', 'Remove coupon button',                                          'Remove'],
            ['checkout.coupon_placeholder',             4, 'checkout.blade.php', 'Coupon input placeholder',                                      'Enter coupon...'],
            ['checkout.coupon_apply',                   4, 'checkout.blade.php', 'Apply coupon button',                                           'Apply'],
            ['checkout.shipping',                       4, 'checkout.blade.php', 'Shipping label in checkout summary',                            'Shipping'],
            ['checkout.coupon_code',                    4, 'checkout.blade.php', 'Coupon code line label',                                        'Coupon Code'],
            ['checkout.subtotal',                       4, 'checkout.blade.php', 'Subtotal label in order summary',                               'Subtotal'],
            ['checkout.discount',                       4, 'checkout.blade.php', 'Discount label in order summary',                               'Discount'],
            ['checkout.shipping_calculated',            4, 'checkout.blade.php', 'Shipping calculated at review note',                            'Calculated at review'],
            ['checkout.total',                          4, 'checkout.blade.php', 'Total label in order summary',                                  'Total'],

            // ── Section 5: Order Review & Success ─────────────────────────
            ['review.page_heading',              5, 'order-review.blade.php',      'Order review page heading',                                   'Order Review & Payment'],
            ['review.delivery_heading',          5, 'order-review.blade.php',      'Delivery information section heading',                        'Delivery Information'],
            ['review.edit_details',              5, 'order-review.blade.php',      'Edit delivery details link',                                  'Edit details'],
            ['review.customer_profile',          5, 'order-review.blade.php',      'Customer profile label',                                      'Customer Profile'],
            ['review.shipping_address',          5, 'order-review.blade.php',      'Shipping address label',                                      'Shipping Address'],
            ['review.fulfillment',               5, 'order-review.blade.php',      'Fulfillment type label',                                      'Fulfillment'],
            ['review.digital_only_message',      5, 'order-review.blade.php',      'Digital only fulfillment message',                            'Order contains digital products only. Instant download links will be generated on completion.'],
            ['review.shipping_method',           5, 'order-review.blade.php',      'Shipping method selection heading',                           'Shipping Method'],
            ['review.free',                      5, 'order-review.blade.php',      'Free shipping label',                                         'Free'],
            ['review.additional_info',           5, 'order-review.blade.php',      'Additional information section heading',                      'Additional Information'],
            ['review.mailing_list',              5, 'order-review.blade.php',      'Mailing list opt-in checkbox label',                          'Yes, add me to the mailing list'],
            ['review.payment_method',            5, 'order-review.blade.php',      'Payment method section heading',                              'Payment Method'],
            ['review.billing_address',           5, 'order-review.blade.php',      'Billing address label',                                       'Billing Address'],
            ['review.payment_details',           5, 'order-review.blade.php',      'Payment details/card label',                                  'Payment Details'],
            ['review.card_details',              5, 'order-review.blade.php',      'Card details fallback label',                                 'Card Details'],
            ['review.stripe_message',            5, 'order-review.blade.php',      'Stripe security message',                                     'Secured by Stripe. Your card details are never stored on our servers.'],
            ['review.test_mode_heading',         5, 'order-review.blade.php',      'Test mode simulator heading',                                 'Test / Simulation Mode'],
            ['review.test_mode_message',         5, 'order-review.blade.php',      'Test mode description message',                               'This checkout is using the built-in test processor. No real payment will be processed. Use the options below to simulate different payment outcomes.'],
            ['review.simulate_success',          5, 'order-review.blade.php',      'Simulate success option label',                               '✓ Simulate Success'],
            ['review.simulate_success_note',     5, 'order-review.blade.php',      'Simulate success description',                                'Order will be placed and confirmed'],
            ['review.simulate_failure',          5, 'order-review.blade.php',      'Simulate failure option label',                               '✗ Simulate Failure'],
            ['review.simulate_failure_note',     5, 'order-review.blade.php',      'Simulate failure description',                                'Payment will be declined'],
            ['review.card_number',               5, 'order-review.blade.php',      'Test mode card number field label',                           'Card Number'],
            ['review.expiry',                    5, 'order-review.blade.php',      'Test mode expiry field label',                                'Expiry'],
            ['review.cvv',                       5, 'order-review.blade.php',      'Test mode CVV field label',                                   'CVV'],
            ['review.zip',                       5, 'order-review.blade.php',      'Test mode ZIP field label',                                   'ZIP'],
            ['review.cardholder_name',           5, 'order-review.blade.php',      'Test mode cardholder name field label',                       'Cardholder Name'],
            ['review.order_comments',            5, 'order-review.blade.php',      'Order comments section heading',                              'Order Comments'],
            ['review.order_comments_placeholder',5, 'order-review.blade.php',      'Order comments textarea placeholder',                         'Add any special instructions or comments about your order here...'],
            ['review.review_items',              5, 'order-review.blade.php',      'Review items section heading',                                'Review Items'],
            ['review.subtotal',                  5, 'order-review.blade.php',      'Subtotal label',                                              'Subtotal'],
            ['review.preferred_discount',        5, 'order-review.blade.php',      'Preferred customer discount label',                           'Preferred Customer Discount'],
            ['review.general_discount',          5, 'order-review.blade.php',      'General order discount label',                                'General Order Discount'],
            ['review.new_customer_promo',        5, 'order-review.blade.php',      'New customer promo label',                                    'New Customer Promo'],
            ['review.promo_discount',            5, 'order-review.blade.php',      'Promo discount label',                                        'Promo Discount'],
            ['review.includes_tax',              5, 'order-review.blade.php',      'Tax included label',                                          'Includes'],
            ['review.handling',                  5, 'order-review.blade.php',      'Handling surcharge label',                                    'Handling Surcharge'],
            ['review.total',                     5, 'order-review.blade.php',      'Total label',                                                 'Total'],
            ['review.place_order',               5, 'order-review.blade.php',      'Place order button',                                          'Place Order'],
            ['review.processing',                5, 'order-review.blade.php',      'Processing state button text',                                'Processing...'],
            ['review.stripe_load_error',         5, 'order-review.blade.php',      'Stripe form load error message',                              'Failed to load Stripe payment form. Please refresh the page.'],
            ['review.paddle_load_error',         5, 'order-review.blade.php',      'Paddle form load error message',                              'Failed to load Paddle payment form.'],
            ['review.paypal_order_error',        5, 'order-review.blade.php',      'PayPal order creation error',                                 'Failed to create PayPal order.'],
            ['review.paypal_capture_error',      5, 'order-review.blade.php',      'PayPal payment capture error',                                'Payment capture failed.'],
            ['review.paypal_cancelled',          5, 'order-review.blade.php',      'PayPal payment cancelled message',                            'Payment cancelled.'],
            ['review.paypal_error',              5, 'order-review.blade.php',      'PayPal generic error message',                                'An error occurred with PayPal.'],
            ['review.paypal_load_error',         5, 'order-review.blade.php',      'PayPal form load error message',                              'Failed to load PayPal checkout. Please refresh the page.'],
            ['success.order_confirmed',          5, 'checkout-success.blade.php',  'Order confirmed heading',                                     'Order Confirmed!'],
            ['success.thank_you_message',        5, 'checkout-success.blade.php',  'Order confirmation body message',                             'Thank you for your purchase. Your payment was processed successfully. A confirmation email has been dispatched.'],
            ['success.order_status',             5, 'checkout-success.blade.php',  'Order status label',                                          'Order Status'],
            ['success.payment_received',         5, 'checkout-success.blade.php',  'Payment received status text',                                'Payment Received - Order Being Processed.'],
            ['success.order_number',             5, 'checkout-success.blade.php',  'Order number label',                                          'Order #'],
            ['success.order_date',               5, 'checkout-success.blade.php',  'Order date label',                                            'Order Date'],
            ['success.customer_name',            5, 'checkout-success.blade.php',  'Customer name label',                                         'Customer Name'],
            ['success.guest_user',               5, 'checkout-success.blade.php',  'Guest user fallback label',                                   'Guest User'],
            ['success.email_address',            5, 'checkout-success.blade.php',  'Email address label',                                         'Email Address'],
            ['success.items_ordered',            5, 'checkout-success.blade.php',  'Items ordered section heading',                               'Items Ordered'],
            ['success.quantity',                 5, 'checkout-success.blade.php',  'Quantity label',                                              'Quantity:'],
            ['success.ready_for_download',       5, 'checkout-success.blade.php',  'Ready for download status',                                   'Ready for download'],
            ['success.download_file',            5, 'checkout-success.blade.php',  'Download file button',                                        'Download File'],
            ['success.will_be_shipped',          5, 'checkout-success.blade.php',  'Will be shipped status',                                      'Will be shipped'],
            ['success.subtotal',                 5, 'checkout-success.blade.php',  'Subtotal label',                                              'Subtotal'],
            ['success.promotional_discount',     5, 'checkout-success.blade.php',  'Promotional discount label',                                  'Promotional Discount'],
            ['success.flat_rate',                5, 'checkout-success.blade.php',  'Flat rate shipping label',                                    'Flat Rate'],
            ['success.handling',                 5, 'checkout-success.blade.php',  'Handling surcharge label',                                    'Handling Surcharge'],
            ['success.total_charged',            5, 'checkout-success.blade.php',  'Total charged label',                                         'Total Charged'],
            ['success.shipping_address',         5, 'checkout-success.blade.php',  'Shipping address heading',                                    'Shipping Address'],
            ['success.order_comments',           5, 'checkout-success.blade.php',  'Order comments heading',                                      'Order Comments'],
            ['post_cart.added_message',          5, 'post-cart-cross-sell.blade.php','Product added to cart message',                             'was added to your cart!'],
            ['post_cart.sku',                    5, 'post-cart-cross-sell.blade.php','SKU label',                                                  'SKU:'],
            ['post_cart.continue_shopping',      5, 'post-cart-cross-sell.blade.php','Continue shopping button',                                   'Continue Shopping'],
            ['post_cart.view_cart',              5, 'post-cart-cross-sell.blade.php','View cart button',                                           'View Cart'],
            ['post_cart.checkout',               5, 'post-cart-cross-sell.blade.php','Checkout button',                                            'Checkout'],

            // ── Section 6: Shop Catalog ────────────────────────────────────
            ['catalog.page_title',           6, 'shop-catalog.blade.php', 'Default shop catalog page title',                   'E-Commerce Products'],
            ['catalog.page_description',     6, 'shop-catalog.blade.php', 'Default shop catalog page description',             'Browse our curated catalog. Enjoy exclusive wholesale pricing if eligible.'],
            ['catalog.notice',               6, 'shop-catalog.blade.php', 'Notice panel heading',                              'Notice'],
            ['catalog.dismiss',              6, 'shop-catalog.blade.php', 'Dismiss notice button',                             'Dismiss'],
            ['catalog.advanced_filters',     6, 'shop-catalog.blade.php', 'Advanced filters toggle button',                    'Advanced Filters'],
            ['catalog.search_placeholder',   6, 'shop-catalog.blade.php', 'Product search input placeholder',                  'Search products...'],
            ['catalog.wholesale_active',     6, 'shop-catalog.blade.php', 'Wholesale account active status',                   'Wholesale Account Active'],
            ['catalog.wholesale_message',    6, 'shop-catalog.blade.php', 'Wholesale pricing notice message',                  'You are seeing wholesale pricing on eligible items.'],
            ['catalog.active_filters',       6, 'shop-catalog.blade.php', 'Active filters label',                              'Active Filters:'],
            ['catalog.filter_category',      6, 'shop-catalog.blade.php', 'Category filter label',                             'Category:'],
            ['catalog.filter_brand',         6, 'shop-catalog.blade.php', 'Brand filter label',                                'Brand:'],
            ['catalog.filter_keyword',       6, 'shop-catalog.blade.php', 'Keyword filter label',                              'Keyword:'],
            ['catalog.filter_price',         6, 'shop-catalog.blade.php', 'Price filter label',                                'Price:'],
            ['catalog.clear_all',            6, 'shop-catalog.blade.php', 'Clear all filters button',                          'Clear All'],
            ['catalog.browse_by_category',   6, 'shop-catalog.blade.php', 'Category browser section heading',                  'Browse by Category'],
            ['catalog.subcategories',        6, 'shop-catalog.blade.php', 'Subcategories section heading',                     'Subcategories'],
            ['catalog.filter_by_brand',      6, 'shop-catalog.blade.php', 'Brand filter section heading',                      'Filter by Brand'],
            ['catalog.showing',              6, 'shop-catalog.blade.php', 'Showing X products label (prefix)',                  'Showing'],
            ['catalog.of',                   6, 'shop-catalog.blade.php', 'Of Y products label (separator)',                   'of'],
            ['catalog.products',             6, 'shop-catalog.blade.php', 'Products label (suffix)',                            'products'],
            ['catalog.no_products_found',    6, 'shop-catalog.blade.php', 'No products found label',                           'No products found'],
            ['catalog.sort',                 6, 'shop-catalog.blade.php', 'Sort by label',                                     'Sort'],
            ['catalog.sort_price_low',       6, 'shop-catalog.blade.php', 'Sort price low to high option',                     'Price Low-High'],
            ['catalog.sort_price_high',      6, 'shop-catalog.blade.php', 'Sort price high to low option',                     'Price High-Low'],
            ['catalog.sort_title_asc',       6, 'shop-catalog.blade.php', 'Sort title A-Z option',                             'Title A-Z (ASC)'],
            ['catalog.sort_title_desc',      6, 'shop-catalog.blade.php', 'Sort title Z-A option',                             'Title Z-A (DESC)'],
            ['catalog.sort_rating_high',     6, 'shop-catalog.blade.php', 'Sort highest to lowest rated option',               'Highest To Lowest Rated'],
            ['catalog.sort_rating_low',      6, 'shop-catalog.blade.php', 'Sort lowest to highest rated option',               'Lowest To Highest Rated'],
            ['catalog.show',                 6, 'shop-catalog.blade.php', 'Show per page label',                               'Show'],
            ['catalog.no_match_heading',     6, 'shop-catalog.blade.php', 'No products match filters heading',                 'No products match your filter criteria'],
            ['catalog.no_match_message',     6, 'shop-catalog.blade.php', 'No products match filters message',                 'Try clearing your active category, brand, search filters, or price slider.'],
            ['catalog.clear_category',       6, 'shop-catalog.blade.php', 'Clear category filter button',                      'Clear Category'],
            ['catalog.clear_brand',          6, 'shop-catalog.blade.php', 'Clear brand filter button',                         'Clear Brand'],
            ['catalog.reset_filters',        6, 'shop-catalog.blade.php', 'Reset all filters button',                          'Reset All Filters'],
            ['catalog.sale',                 6, 'shop-catalog.blade.php', 'Sale badge on product card',                        'Sale'],
            ['catalog.buy_now',              6, 'shop-catalog.blade.php', 'Buy now button on product card',                    'Buy Now'],
            ['catalog.out_of_stock',         6, 'shop-catalog.blade.php', 'Out of stock status on product card',               'Out of Stock'],
            ['catalog.price_range',          6, 'shop-catalog.blade.php', 'Price range filter section heading',                'Price Range Filter'],
            ['catalog.min_price',            6, 'shop-catalog.blade.php', 'Min price filter label',                            'Min Price'],
            ['catalog.max_price',            6, 'shop-catalog.blade.php', 'Max price filter label',                            'Max Price'],
            ['catalog.filter_by_categories', 6, 'shop-catalog.blade.php', 'Filter by categories section heading',              'Filter by Categories'],
            ['catalog.filter_by_brands',     6, 'shop-catalog.blade.php', 'Filter by brands section heading',                  'Filter by Brands'],
            ['catalog.apply_view',           6, 'shop-catalog.blade.php', 'Apply and view results button',                     'Apply & View'],

            // ── Section 7: Product Details & Buy Box ──────────────────────
            ['product.breadcrumb_shop',           7, 'product-details.blade.php',        'Shop breadcrumb link',                              'Shop'],
            ['product.admin_edit_button',         7, 'product-details.blade.php',        'Admin edit product button',                         'Edit Product (Admin)'],
            ['product.recommendations',           7, 'product-details.blade.php',        'Product recommendations section heading',            'Product recommendations for you'],
            ['product.view',                      7, 'product-details.blade.php',        'View product link text',                            'View'],
            ['product.price',                     7, 'product-buy-box.blade.php',        'Price label in buy box',                            'Price'],
            ['product.each',                      7, 'product-buy-box.blade.php',        'Per-unit price suffix label',                       '/each'],
            ['product.save',                      7, 'product-buy-box.blade.php',        'Save amount label',                                 'Save'],
            ['product.selection_fee',             7, 'product-buy-box.blade.php',        'Selection fee included label',                      'selection fee included'],
            ['product.wholesale_rate',            7, 'product-buy-box.blade.php',        'Wholesale rate status badge',                       'Wholesale Rate'],
            ['product.in_stock',                  7, 'product-buy-box.blade.php',        'In stock status label',                             'in stock'],
            ['product.out_of_stock',              7, 'product-buy-box.blade.php',        'Out of stock status label',                         'Out of stock'],
            ['product.digital_item',              7, 'product-buy-box.blade.php',        'Digital item status label',                         'Digital Item (Instant Download)'],
            ['product.customize_heading',         7, 'product-buy-box.blade.php',        'Customize product section heading',                 'Customize Product'],
            ['product.customize_message',         7, 'product-buy-box.blade.php',        'Customize product prompt message',                  'Please customize your selection below before adding to cart.'],
            ['product.field_required',            7, 'product-buy-box.blade.php',        'Required field indicator label',                    '(Required)'],
            ['product.field_enter_details',       7, 'product-buy-box.blade.php',        'Enter details field placeholder',                   'Enter details...'],
            ['product.field_select_option',       7, 'product-buy-box.blade.php',        'Select option dropdown placeholder',                '-- Select option --'],
            ['product.gift_wrapping',             7, 'product-buy-box.blade.php',        'Gift wrapping/personalization toggle label',        'Add Gift Wrapping / Personalization'],
            ['product.personalization',           7, 'product-buy-box.blade.php',        'Personalization details field label',               'Personalization Details / Gift Message'],
            ['product.personalization_placeholder',7,'product-buy-box.blade.php',        'Personalization textarea placeholder',              'Enter names for engraving, personalization details, or a custom gift message here...'],
            ['product.quantity',                  7, 'product-buy-box.blade.php',        'Quantity field label',                              'Quantity'],
            ['product.add_to_cart',               7, 'product-buy-box.blade.php',        'Add to cart button',                                'Add to Cart'],
            ['product.adding',                    7, 'product-buy-box.blade.php',        'Adding to cart button state',                       'Adding...'],
            ['product.cart_error',                7, 'product-buy-box.blade.php',        'Cart error message prefix',                         'Could not add item to cart:'],
            ['product.item_total',                7, 'product-buy-box.blade.php',        'Item total display label',                          'Item Total'],
            ['product.unavailable',               7, 'product-buy-box.blade.php',        'Currently unavailable button text',                 'Currently Unavailable'],
            ['product.gallery_zoom_hint',         7, 'product-gallery.blade.php',        'Gallery zoom hint text',                            'Hover to zoom · Click to enlarge'],
            ['product.video_preview',             7, 'product-video-player.blade.php',   'Video preview section heading',                     'Video Preview'],
            ['product.watch_video',               7, 'product-video-player.blade.php',   'Watch video label',                                 'Watch video:'],
            ['reviews.based_on',                  7, 'product-reviews-list.blade.php',   'Reviews count prefix label',                        'Based on'],
            ['reviews.sort',                      7, 'product-reviews-list.blade.php',   'Sort reviews label',                                'Sort Reviews'],
            ['reviews.most_recent',               7, 'product-reviews-list.blade.php',   'Most recent sort option',                           'Most Recent'],
            ['reviews.highest_rated',             7, 'product-reviews-list.blade.php',   'Highest rated sort option',                         'Highest Rated'],
            ['reviews.lowest_rated',              7, 'product-reviews-list.blade.php',   'Lowest rated sort option',                          'Lowest Rated'],
            ['reviews.no_reviews',                7, 'product-reviews-list.blade.php',   'No reviews empty state heading',                    'No reviews yet'],
            ['reviews.no_reviews_message',        7, 'product-reviews-list.blade.php',   'No reviews empty state message',                    'Be the first to share your thoughts by filling out the form below.'],
            ['reviews.leave_review',              7, 'product-reviews-list.blade.php',   'Leave a review section heading',                    'Leave a Review'],
            ['reviews.leave_review_message',      7, 'product-reviews-list.blade.php',   'Leave review prompt message',                       'Share your feedback regarding your purchase with other customers.'],
            ['reviews.your_rating',               7, 'product-reviews-list.blade.php',   'Star rating field label',                           'Your Rating'],
            ['reviews.your_name',                 7, 'product-reviews-list.blade.php',   'Reviewer name field label',                         'Your Name (Required)'],
            ['reviews.name_placeholder',          7, 'product-reviews-list.blade.php',   'Reviewer name field placeholder',                   'e.g. John Doe'],
            ['reviews.location',                  7, 'product-reviews-list.blade.php',   'Reviewer location field label',                     'Location (Optional)'],
            ['reviews.location_placeholder',      7, 'product-reviews-list.blade.php',   'Reviewer location field placeholder',               'e.g. New York, NY'],
            ['reviews.comments',                  7, 'product-reviews-list.blade.php',   'Review comments field label',                       'Comments (Optional)'],
            ['reviews.comments_placeholder',      7, 'product-reviews-list.blade.php',   'Review comments field placeholder',                 'Describe your experience with this product...'],
            ['reviews.submit',                    7, 'product-reviews-list.blade.php',   'Submit review button',                              'Submit Review'],

            // ── Section 8: My Account & Dashboard ─────────────────────────
            ['account.my_account',               8, 'user-dashboard.blade.php', 'My Account heading',                                          'My Account'],
            ['account.signed_in_as',             8, 'user-dashboard.blade.php', 'Signed in as label',                                          'Signed in as'],
            ['account.edit_profile',             8, 'user-dashboard.blade.php', 'Edit profile navigation link',                                'Edit Profile'],
            ['account.sign_out',                 8, 'user-dashboard.blade.php', 'Sign out button',                                             'Sign Out'],
            ['account.new_ticket',               8, 'user-dashboard.blade.php', 'New ticket button',                                           'New Ticket'],
            ['account.orders_tab',               8, 'user-dashboard.blade.php', 'Orders tab label',                                            'Orders'],
            ['account.downloads_tab',            8, 'user-dashboard.blade.php', 'Downloads tab label',                                         'Downloads'],
            ['account.support_tab',              8, 'user-dashboard.blade.php', 'Support Tickets tab label',                                   'Support Tickets'],
            ['account.order_detail',             8, 'user-dashboard.blade.php', 'Order detail heading',                                        'Order Detail'],
            ['account.back_to_list',             8, 'user-dashboard.blade.php', 'Back to list button',                                         'Back to List'],
            ['account.col_product',              8, 'user-dashboard.blade.php', 'Product column header',                                       'Product'],
            ['account.col_qty',                  8, 'user-dashboard.blade.php', 'Qty column header',                                           'Qty'],
            ['account.col_price',                8, 'user-dashboard.blade.php', 'Price column header',                                         'Price'],
            ['account.col_total',                8, 'user-dashboard.blade.php', 'Total column header',                                         'Total'],
            ['account.digital_delivery',         8, 'user-dashboard.blade.php', 'Digital delivery badge in order detail',                      'Digital Delivery'],
            ['account.subtotal',                 8, 'user-dashboard.blade.php', 'Subtotal label in order summary',                             'Subtotal:'],
            ['account.discounts',                8, 'user-dashboard.blade.php', 'Discounts label in order summary',                            'Discounts:'],
            ['account.shipping',                 8, 'user-dashboard.blade.php', 'Shipping label in order summary',                             'Shipping:'],
            ['account.tax',                      8, 'user-dashboard.blade.php', 'Tax label in order summary',                                  'Tax:'],
            ['account.status_label',             8, 'user-dashboard.blade.php', 'Status label in order summary',                               'Status:'],
            ['account.your_orders',              8, 'user-dashboard.blade.php', 'Your orders section heading',                                  'Your Orders'],
            ['account.showing',                  8, 'user-dashboard.blade.php', 'Showing X records prefix',                                    'Showing'],
            ['account.of',                       8, 'user-dashboard.blade.php', 'Of Y records separator',                                      'of'],
            ['account.orders',                   8, 'user-dashboard.blade.php', 'Orders suffix in count',                                      'orders'],
            ['account.col_order',                8, 'user-dashboard.blade.php', 'Order number column header',                                   'Order #'],
            ['account.col_date',                 8, 'user-dashboard.blade.php', 'Date column header',                                           'Date'],
            ['account.col_status',               8, 'user-dashboard.blade.php', 'Status column header',                                         'Status'],
            ['account.col_action',               8, 'user-dashboard.blade.php', 'Action column header',                                         'Action'],
            ['account.view_details',             8, 'user-dashboard.blade.php', 'View order details button',                                    'View Details'],
            ['account.no_orders',                8, 'user-dashboard.blade.php', 'No orders empty state heading',                                'No orders found'],
            ['account.no_orders_message',        8, 'user-dashboard.blade.php', 'No orders empty state message',                                "You haven't placed any orders yet. Visit our shop to browse products."],
            ['account.browse_shop',              8, 'user-dashboard.blade.php', 'Browse shop button',                                           'Browse Shop'],
            ['account.your_downloads',           8, 'user-dashboard.blade.php', 'Your downloads section heading',                               'Your Downloads'],
            ['account.col_file_name',            8, 'user-dashboard.blade.php', 'File name column header',                                      'File Name'],
            ['account.col_expires',              8, 'user-dashboard.blade.php', 'Expires column header',                                        'Expires'],
            ['account.never',                    8, 'user-dashboard.blade.php', 'Never expires label',                                          'Never'],
            ['account.expired',                  8, 'user-dashboard.blade.php', 'Expired download status',                                      'Expired'],
            ['account.download',                 8, 'user-dashboard.blade.php', 'Download file button',                                         'Download'],
            ['account.no_downloads',             8, 'user-dashboard.blade.php', 'No downloads empty state heading',                             'No downloads available'],
            ['account.no_downloads_message',     8, 'user-dashboard.blade.php', 'No downloads empty state message',                             "You haven't purchased any digital items yet, or access has expired."],
            ['account.total_tickets',            8, 'user-dashboard.blade.php', 'Total tickets stat label',                                     'Total Tickets'],
            ['account.open_in_process',          8, 'user-dashboard.blade.php', 'Open & in process tickets stat label',                         'Open & In Process'],
            ['account.completed',                8, 'user-dashboard.blade.php', 'Completed tickets stat label',                                  'Completed'],
            ['account.closed',                   8, 'user-dashboard.blade.php', 'Closed tickets stat label',                                    'Closed'],
            ['account.support_history',          8, 'user-dashboard.blade.php', 'Support history section heading',                              'Support History'],
            ['account.col_ticket',               8, 'user-dashboard.blade.php', 'Ticket column header',                                         'Ticket'],
            ['account.col_replies',              8, 'user-dashboard.blade.php', 'Replies column header',                                        'Replies'],
            ['account.col_updated',              8, 'user-dashboard.blade.php', 'Updated column header',                                        'Updated'],
            ['account.no_replies',               8, 'user-dashboard.blade.php', 'Zero replies label',                                           '0 replies'],
            ['account.view',                     8, 'user-dashboard.blade.php', 'View ticket button',                                           'View'],
            ['account.no_tickets',               8, 'user-dashboard.blade.php', 'No tickets empty state heading',                               'No tickets yet'],
            ['account.no_tickets_message',       8, 'user-dashboard.blade.php', 'No tickets empty state message',                               'If you need help or have a question, submit your first ticket to contact support.'],
            ['account.submit_ticket',            8, 'user-dashboard.blade.php', 'Submit ticket button',                                         'Submit Ticket'],

            // ── Section 9: Support & Tickets ──────────────────────────────
            ['ticket.create_heading',         9, 'create-ticket.blade.php',     'Create ticket page heading',                                    'Submit Support Ticket'],
            ['ticket.create_message',         9, 'create-ticket.blade.php',     'Create ticket prompt message',                                  "Describe your issue and we'll get back to you as soon as possible."],
            ['ticket.subject',                9, 'create-ticket.blade.php',     'Subject field label',                                           'Subject / Ticket Title'],
            ['ticket.subject_placeholder',    9, 'create-ticket.blade.php',     'Subject field placeholder',                                     "e.g. Can't access billing portal or load invoices"],
            ['ticket.description',            9, 'create-ticket.blade.php',     'Description field label',                                       'Detailed Description'],
            ['ticket.description_placeholder',9, 'create-ticket.blade.php',     'Description field placeholder',                                 'Describe what went wrong, what steps you were taking, and any error messages you saw.'],
            ['ticket.attachments',            9, 'create-ticket.blade.php',     'Attachments field label',                                       'Attachments (optional)'],
            ['ticket.upload_files',           9, 'create-ticket.blade.php',     'Upload files button/label',                                     'Upload files'],
            ['ticket.or_drag_drop',           9, 'create-ticket.blade.php',     'Drag and drop label',                                           'or drag and drop'],
            ['ticket.files_selected',         9, 'create-ticket.blade.php',     'Files selected section heading',                                'Files Selected (Ready to Upload)'],
            ['ticket.cancel',                 9, 'create-ticket.blade.php',     'Cancel button',                                                 'Cancel'],
            ['ticket.submit',                 9, 'create-ticket.blade.php',     'Submit ticket button',                                          'Submit Ticket'],
            ['ticket.submitting',             9, 'create-ticket.blade.php',     'Submitting state text',                                         'Submitting...'],
            ['ticket.original_request',       9, 'show-ticket.blade.php',       'Original request section label',                                'Original Request'],
            ['ticket.replies_heading',        9, 'show-ticket.blade.php',       'Replies section heading',                                       'Replies & Updates'],
            ['ticket.support_agent',          9, 'show-ticket.blade.php',       'Support agent label',                                           'Support Agent'],
            ['ticket.no_replies',             9, 'show-ticket.blade.php',       'No replies yet message',                                        "No replies recorded yet. You'll receive email updates as our team reviews your request."],
            ['ticket.post_reply',             9, 'show-ticket.blade.php',       'Post a reply section heading',                                  'Post a Reply'],
            ['ticket.reply_placeholder',      9, 'show-ticket.blade.php',       'Reply textarea placeholder',                                    'Type your reply here...'],
            ['ticket.upload_optional',        9, 'show-ticket.blade.php',       'Optional upload label',                                         'Upload Files (optional)'],
            ['ticket.files_selected_label',   9, 'show-ticket.blade.php',       'Files selected count label',                                    'Files selected:'],
            ['ticket.send_message',           9, 'show-ticket.blade.php',       'Send message button',                                           'Send Message'],
            ['ticket.sending',                9, 'show-ticket.blade.php',       'Sending state text',                                            'Sending...'],
            ['ticket.closed_heading',         9, 'show-ticket.blade.php',       'Closed ticket notice heading',                                  'This ticket is closed'],
            ['ticket.closed_message',         9, 'show-ticket.blade.php',       'Closed ticket notice message',                                  'Replies are disabled. If you have further issues, please submit a new ticket.'],
            ['ticket.info_heading',           9, 'show-ticket.blade.php',       'Ticket information section heading',                            'Ticket Information'],
            ['ticket.assigned_agent',         9, 'show-ticket.blade.php',       'Assigned agent label',                                          'Assigned Agent'],
            ['ticket.unassigned',             9, 'show-ticket.blade.php',       'Unassigned agent label',                                        'Unassigned'],
            ['ticket.last_activity',          9, 'show-ticket.blade.php',       'Last activity label',                                           'Last Activity'],
            ['ticket.reply_via_email',        9, 'show-ticket.blade.php',       'Reply via email label',                                         'Reply via Email'],
            ['ticket.reply_via_email_note',   9, 'show-ticket.blade.php',       'Reply via email instruction',                                   'Send mail to this address to post replies directly.'],
            ['ticket.secure_link',            9, 'show-ticket.blade.php',       'Secure public link heading',                                    'Secure Public Link'],
            ['ticket.secure_link_message',    9, 'show-ticket.blade.php',       'Secure link description message',                               'Share this secret URL to access this ticket without needing to log in.'],
            ['ticket.copy_link',              9, 'show-ticket.blade.php',       'Copy link button',                                              'Copy Link'],
            ['ticket.copied',                 9, 'show-ticket.blade.php',       'Copied confirmation text',                                      'Copied!'],
            ['ticket.public_portal',          9, 'public-ticket-view.blade.php','Public ticket portal label',                                    'Secure Ticket Portal'],

            // ── Section 10: Knowledge Base ─────────────────────────────────
            ['kb.help_heading',        10, 'kb-landing.blade.php',     'KB landing page main heading',                                          'How can we help you today?'],
            ['kb.help_message',        10, 'kb-landing.blade.php',     'KB landing page description',                                           'Search our knowledge base for guides, FAQs, and step-by-step instructions to solve support queries quickly.'],
            ['kb.browse_by_category',  10, 'kb-landing.blade.php',     'Browse by category section heading',                                    'Browse by Category'],
            ['kb.search_results',      10, 'kb-landing.blade.php',     'Search results section heading',                                        'Search Results'],
            ['kb.popular_articles',    10, 'kb-landing.blade.php',     'Popular articles section heading',                                      'Top 15 Most Popular Articles'],
            ['kb.no_articles',         10, 'kb-landing.blade.php',     'No articles found empty state',                                         'No articles found'],
            ['kb.no_match_message',    10, 'kb-landing.blade.php',     'No articles matching search message',                                   "We couldn't find any articles matching"],
            ['kb.clear_search',        10, 'kb-landing.blade.php',     'Clear search filter button',                                            'Clear Search Filter'],
            ['kb.added',               10, 'kb-landing.blade.php',     'Article added date label',                                              'Added'],
            ['kb.read_article',        10, 'kb-landing.blade.php',     'Read article button',                                                   'Read Article'],
            ['kb.breadcrumb',          10, 'kb-article-show.blade.php','Knowledge Base breadcrumb link',                                        'Knowledge Base'],
            ['kb.published',           10, 'kb-article-show.blade.php','Article published date label',                                          'Published'],
            ['kb.updated',             10, 'kb-article-show.blade.php','Article updated date label',                                            'Updated'],
            ['kb.helpful_heading',     10, 'kb-article-show.blade.php','Was this helpful section heading',                                      'Was this article helpful?'],
            ['kb.helpful_message',     10, 'kb-article-show.blade.php','Helpful prompt message',                                                'Let us know how we can improve our documentation.'],
            ['kb.helpful_yes',         10, 'kb-article-show.blade.php','Yes helpful button',                                                    'Yes, thanks!'],
            ['kb.helpful_no',          10, 'kb-article-show.blade.php','No helpful button',                                                     "No, it didn't help"],
            ['kb.thanks_positive',     10, 'kb-article-show.blade.php','Positive feedback thank you message',                                   'Thank you for your positive feedback!'],
            ['kb.thanks_improve',      10, 'kb-article-show.blade.php','Improvement feedback thank you message',                                'Thank you! We will update this guide soon.'],
            ['kb.back_to_all',         10, 'kb-article-show.blade.php','Back to all articles navigation',                                       'Back to All Articles'],
            ['kb.search_placeholder',  10, 'kb-search-bar.blade.php',  'Knowledge base search bar placeholder',                                 'Type keywords (e.g. password, billing, attachment)...'],

            // ── Section 11: Auth Pages ─────────────────────────────────────
            ['auth.login_heading',           11, 'login.blade.php',                        'Login page heading',                                        'Welcome back'],
            ['auth.login_message',           11, 'login.blade.php',                        'Login page subheading message',                             'Sign in to your account to continue'],
            ['auth.email',                   11, 'login.blade.php',                        'Email address field label',                                 'Email Address'],
            ['auth.email_placeholder',       11, 'login.blade.php',                        'Email address field placeholder',                           'you@example.com'],
            ['auth.password',                11, 'login.blade.php',                        'Password field label',                                      'Password'],
            ['auth.forgot_password',         11, 'login.blade.php',                        'Forgot password link',                                      'Forgot password?'],
            ['auth.remember_me',             11, 'login.blade.php',                        'Remember me checkbox label',                                'Keep me signed in'],
            ['auth.sign_in',                 11, 'login.blade.php',                        'Sign in button',                                            'Sign In'],
            ['auth.signing_in',              11, 'login.blade.php',                        'Signing in loading state',                                  'Signing in…'],
            ['auth.or_continue_with',        11, 'login.blade.php',                        'Social login divider',                                      'or continue with'],
            ['auth.no_account',              11, 'login.blade.php',                        'No account message',                                        "Don't have an account?"],
            ['auth.create_one',              11, 'login.blade.php',                        'Create account link',                                       'Create one free'],
            ['auth.register_heading',        11, 'register.blade.php',                     'Register page heading',                                     'Create your account'],
            ['auth.full_name',               11, 'register.blade.php',                     'Full name field label',                                     'Full Name'],
            ['auth.full_name_placeholder',   11, 'register.blade.php',                     'Full name field placeholder',                               'Jane Smith'],
            ['auth.password_placeholder',    11, 'register.blade.php',                     'Password field placeholder',                                'Strong Password Required (min 8 char)'],
            ['auth.repeat_password',         11, 'register.blade.php',                     'Confirm password field placeholder',                        'Repeat your password'],
            ['auth.confirm_password',        11, 'register.blade.php',                     'Confirm password field label',                              'Confirm Password'],
            ['auth.create_account',          11, 'register.blade.php',                     'Create account button',                                     'Create Account'],
            ['auth.creating_account',        11, 'register.blade.php',                     'Creating account loading state',                            'Creating account…'],
            ['auth.or_register_with',        11, 'register.blade.php',                     'Social registration divider',                               'or register with'],
            ['auth.have_account',            11, 'register.blade.php',                     'Already have account message',                              'Already have an account?'],
            ['auth.sign_in_link',            11, 'register.blade.php',                     'Sign in link text',                                         'Sign in'],
            ['auth.forgot_heading',          11, 'forgot-password.blade.php',              'Forgot password page heading',                              'Reset your password'],
            ['auth.forgot_message',          11, 'forgot-password.blade.php',              'Forgot password page message',                              "Enter your email and we'll send you a secure reset link."],
            ['auth.send_reset',              11, 'forgot-password.blade.php',              'Send reset link button',                                    'Send Reset Link'],
            ['auth.sending',                 11, 'forgot-password.blade.php',              'Sending loading state',                                     'Sending…'],
            ['auth.remember_password',       11, 'forgot-password.blade.php',              'Remember password message',                                 'Remember your password?'],
            ['auth.reset_heading',           11, 'reset-password.blade.php',               'Reset password page heading',                               'Reset Password'],
            ['auth.verify_heading',          11, 'verify-email.blade.php',                 'Verify email page heading',                                 'Verify Your Email Address'],
            ['auth.check_email',             11, 'verify-email.blade.php',                 'Check email heading',                                       'Check Your Email'],
            ['auth.verify_sent',             11, 'verify-email.blade.php',                 'Verification sent message prefix',                          'We sent a verification link to'],
            ['auth.verify_click',            11, 'verify-email.blade.php',                 'Click link instruction',                                    'Click the link in that email to activate your account.'],
            ['auth.resend_verification',     11, 'verify-email.blade.php',                 'Resend verification email button',                          'Resend Verification Email'],
            ['auth.resend_sending',          11, 'verify-email.blade.php',                 'Resending state text',                                      'Sending...'],
            ['auth.signed_in_as',            11, 'verify-email.blade.php',                 'Signed in as label',                                        'Signed in as'],
            ['auth.sign_out_link',           11, 'verify-email.blade.php',                 'Sign out link text',                                        'Sign out'],
            ['auth.confirm_area',            11, 'confirm-password.blade.php',             'Confirm password security area message',                    'This is a secure area of the application. Please confirm your password before continuing.'],
            ['auth.confirm_button',          11, 'confirm-password.blade.php',             'Confirm button',                                            'Confirm'],
            ['auth.collect_email_heading',   11, 'collect-email.blade.php',                'Collect email heading',                                     'Provide your email address'],
            ['auth.collect_email_message',   11, 'collect-email.blade.php',                'Collect email body message',                                "We couldn't retrieve an email from your provider. Please enter one to complete your registration."],
            ['auth.complete_registration',   11, 'collect-email.blade.php',                'Complete registration button',                              'Complete Registration'],
            ['auth.saving_email',            11, 'collect-email.blade.php',                'Saving email loading state',                                'Saving email…'],
            ['auth.cancel_go_back',          11, 'collect-email.blade.php',                'Cancel and go back link',                                   'Cancel and go back'],
            ['profile.profile_info',         11, 'update-profile-information-form.blade.php','Profile information section heading',                     'Profile Information'],
            ['profile.profile_info_message', 11, 'update-profile-information-form.blade.php','Profile information section message',                     "Update your account's profile information and email address."],
            ['profile.name',                 11, 'update-profile-information-form.blade.php','Name field label',                                        'Name'],
            ['profile.email',                11, 'update-profile-information-form.blade.php','Email field label',                                       'Email'],
            ['profile.unverified',           11, 'update-profile-information-form.blade.php','Email unverified message',                                'Your email address is unverified.'],
            ['profile.resend_verification',  11, 'update-profile-information-form.blade.php','Resend verification link',                                'Click here to re-send the verification email.'],
            ['profile.save',                 11, 'update-profile-information-form.blade.php','Save button',                                             'Save'],
            ['profile.saved',                11, 'update-profile-information-form.blade.php','Saved confirmation',                                      'Saved.'],
            ['profile.update_password',      11, 'update-password-form.blade.php',          'Update password section heading',                          'Update Password'],
            ['profile.update_password_message',11,'update-password-form.blade.php',         'Update password section message',                          'Ensure your account is using a long, random password to stay secure.'],
            ['profile.current_password',     11, 'update-password-form.blade.php',          'Current password field label',                             'Current Password'],
            ['profile.new_password',         11, 'update-password-form.blade.php',          'New password field label',                                 'New Password'],
            ['profile.delete_account',       11, 'delete-user-form.blade.php',              'Delete account section heading',                           'Delete Account'],
            ['profile.delete_confirm_heading',11,'delete-user-form.blade.php',              'Delete account confirm dialog heading',                    'Are you sure you want to delete your account?'],
            ['profile.cancel',               11, 'delete-user-form.blade.php',              'Cancel button',                                            'Cancel'],

            // ── Section 12: CMS Pages ──────────────────────────────────────
            ['cms.author',                   12, 'cms.blade.php',             'Author label',                                                       'Author'],
            ['cms.system',                   12, 'cms.blade.php',             'System author label',                                                'System'],
            ['cms.published_by',             12, 'cms.blade.php',             'Published by label',                                                 'Published By'],
            ['cms.tags',                     12, 'cms.blade.php',             'Tags label',                                                         'Tags:'],
            ['cms.edit_page',                12, 'cms.blade.php',             'Admin edit page button',                                             'Edit Page'],
            ['cms.access_required',          12, 'cms-password.blade.php',    'Access required page heading',                                       'Access Required'],
            ['cms.already_purchased',        12, 'cms-password.blade.php',    'Already purchased content heading',                                  'Already purchased this content?'],
            ['cms.login_for_access',         12, 'cms-password.blade.php',    'Login for access message',                                           'Log in to your account and you will be granted access automatically.'],
            ['cms.access_code',              12, 'cms-password.blade.php',    'Access code field label',                                            'Access Code'],
            ['cms.access_code_placeholder',  12, 'cms-password.blade.php',    'Access code field placeholder',                                      'Enter access code'],
            ['cms.unlock_content',           12, 'cms-password.blade.php',    'Unlock content button',                                              'Unlock Content'],
            ['cms.or',                       12, 'cms-password.blade.php',    'Or divider label',                                                   'or'],
            ['cms.login_to_verify',          12, 'cms-password.blade.php',    'Login to verify purchase button',                                    'Log in to verify purchase'],
            ['cms.category_archives',        12, 'cms-category.blade.php',    'Category archives label',                                            'Category Archives'],
            ['cms.no_content',               12, 'cms-category.blade.php',    'No content available empty state',                                   'No content available'],
            ['cms.tag_archives',             12, 'cms-tag.blade.php',         'Tag archives label',                                                 'Tag Archives'],

            // ── Section 13: Plugin Display Templates ──────────────────────
            ['plugin.sale',                  13, 'featured-items-grid.blade.php',         'Sale badge on plugin product card',            'Sale'],
            ['plugin.from',                  13, 'featured-items-grid.blade.php',         'From price prefix label',                      'From'],
            ['plugin.out_of_stock',          13, 'featured-items-grid.blade.php',         'Out of stock button/status in plugins',        'Out of Stock'],
            ['plugin.buy_now',               13, 'featured-items-grid.blade.php',         'Buy now button in plugins',                    'Buy Now'],
            ['plugin.adding',                13, 'featured-items-grid.blade.php',         'Adding to cart state text in plugins',         'Adding...'],
            ['plugin.view_options',          13, 'featured-items-grid.blade.php',         'View options button in plugins',               'View Options'],
            ['plugin.options',               13, 'featured-items-grid.blade.php',         'Options short button label in plugins',        'Options'],
            ['plugin.variants_available',    13, 'featured-items-grid.blade.php',         'Variants available label in plugins',          'variants available'],
            ['plugin.featured',              13, 'featured-items-grid.blade.php',         'Featured badge in plugins',                    '★ Featured'],
            ['plugin.book_event',            13, 'events-calendar.blade.php',             'Book event button',                            'Book Event'],
            ['plugin.ticket_price',          13, 'events-calendar.blade.php',             'Event ticket price label',                     'Ticket Price'],
            ['plugin.today',                 13, 'events-calendar.blade.php',             'Today navigation button',                      'Today'],
            ['plugin.month_view',            13, 'events-calendar.blade.php',             'Month view tab',                               'Month'],
            ['plugin.agenda_view',           13, 'events-calendar.blade.php',             'Agenda view tab',                              'Agenda'],
            ['plugin.cards_view',            13, 'events-calendar.blade.php',             'Cards view tab',                               'Cards'],
            ['plugin.close',                 13, 'events-calendar.blade.php',             'Close button in event modal',                  'Close'],

            // ── Section 14: Live Search Plugin ─────────────────────────────
            ['live_search.button_label',          14, 'LiveSearchPlugin.php', 'Search button label', 'Search'],
            ['live_search.placeholder',           14, 'LiveSearchPlugin.php', 'Search input placeholder', 'Search products, pages, articles...'],
            ['live_search.loading_message',       14, 'LiveSearchPlugin.php', 'Loading message', 'Searching catalog & articles...'],
            ['live_search.no_results_inline',     14, 'LiveSearchPlugin.php', 'Inline no results message', 'No active results found for'],
            ['live_search.type_product',          14, 'LiveSearchPlugin.php', 'Product type label', 'Product'],
            ['live_search.type_page',             14, 'LiveSearchPlugin.php', 'Site Page type label', 'Site Page'],
            ['live_search.type_kb',               14, 'LiveSearchPlugin.php', 'Knowledge Base type label', 'Knowledge Base'],
            ['live_search.type_testimonial',      14, 'LiveSearchPlugin.php', 'Testimonial type label', 'Testimonial'],
            ['live_search.type_category',         14, 'LiveSearchPlugin.php', 'Category type label', 'Category'],
            ['live_search.type_brand',            14, 'LiveSearchPlugin.php', 'Brand type label', 'Brand'],
            ['live_search.results_heading',       14, 'LiveSearchPlugin.php', 'Results page heading', 'Catalog & Content Search'],
            ['live_search.results_showing',       14, 'LiveSearchPlugin.php', 'Results showing message', 'Showing result(s) for'],
            ['live_search.results_subtitle',      14, 'LiveSearchPlugin.php', 'Results subtitle empty query', 'Enter a keyword below to search across products, CMS pages, documentation, and customer reviews.'],
            ['live_search.start_title',           14, 'LiveSearchPlugin.php', 'Start search title', 'Start Your Search'],
            ['live_search.start_subtitle',        14, 'LiveSearchPlugin.php', 'Start search subtitle', 'Type a product title, page name, or article keyword in the search box above.'],
            ['live_search.no_results_title',      14, 'LiveSearchPlugin.php', 'No results page title', 'No Matching Results Found'],
            ['live_search.no_results_body',       14, 'LiveSearchPlugin.php', 'No results page body', "We couldn't find anything matching your search. Try broader terms or check spelling."],
            ['live_search.browse_catalog',        14, 'LiveSearchPlugin.php', 'Browse catalog button', 'Browse Full Catalog'],
            ['live_search.view_details',          14, 'LiveSearchPlugin.php', 'View details link', 'View Details'],
            ['live_search.cat_snippet_prefix',    14, 'LiveSearchPlugin.php', 'Category snippet prefix', 'Shop items in'],
            ['live_search.brand_snippet_prefix',  14, 'LiveSearchPlugin.php', 'Brand snippet prefix', 'Explore products'],
        ];
    }
}
