<?php

namespace App\Services\Payments\Processors;

use App\Services\Payments\Contracts\PaymentProcessorInterface;
use App\Services\Payments\PaymentResult;
use App\Models\ProductVariant;

/**
 * PaddleProcessor — built-in Paddle Billing payment processor driver.
 *
 * This class is always available as a default processor (processor_id = 2).
 * It is PSR-4 autoloaded from app/Services/Payments/Processors/.
 *
 * CUSTOMISATION
 * ─────────────
 * Do NOT edit this file directly — it may be overwritten by platform updates.
 * To extend or override behaviour, create:
 *
 *   payment-processors/paddle/PaddleProcessorExtension.php
 *
 * If that file exists, it is loaded automatically and used in place of this
 * class for processor_id = 2. See payment-processors/paddle/README.md for
 * a full extension template with examples.
 *
 * CREDENTIALS
 * ───────────
 * Add to .env (sandbox and/or production):
 *
 *   PADDLE_API_KEY=your_live_api_key
 *   PADDLE_CLIENT_TOKEN=your_live_client_token
 *   PADDLE_SANDBOX_API_KEY=your_sandbox_api_key
 *   PADDLE_SANDBOX_CLIENT_TOKEN=your_sandbox_client_token
 *   PADDLE_WEBHOOK_SECRET=pdl_ntf_xxxxxxxxxxxxxxxx
 *
 * SDK
 * ───
 *   composer require paddlehq/paddle-php-sdk
 */
class PaddleProcessor implements PaymentProcessorInterface
{
    public function __construct(private readonly bool $sandbox) {}

    // ─────────────────────────────────────────────────────────────────────────
    // PaymentProcessorInterface implementation
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Verify a Paddle transaction after client-side Paddle.js checkout.
     *
     * $payload = ['transaction_id' => 'txn_xxxx']
     */
    public function charge(float $amount, string $currency, array $payload): PaymentResult
    {
        $transactionId = $payload['transaction_id'] ?? null;

        if (empty($transactionId)) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'No Paddle transaction ID received.',
                processorName:     $this->getName(),
            );
        }

        try {
            $paddle      = $this->client();
            $transaction = $paddle->transactions->get($transactionId);

            $validStatuses = ['completed', 'paid'];
            if (! in_array($transaction->status->getValue(), $validStatuses, true)) {
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    transactionId:     $transactionId,
                    errorMessage:      'Paddle transaction status: ' . $transaction->status->getValue(),
                    processorName:     $this->getName(),
                );
            }

            return new PaymentResult(
                success:           true,
                authorizationCode: $transaction->id,
                transactionId:     $transactionId,
                processorName:     $this->getName(),
            );

        } catch (\Paddle\SDK\Exceptions\ApiError $e) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'Paddle API error: ' . $e->getMessage(),
                processorName:     $this->getName(),
            );
        } catch (\Throwable $e) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'Paddle verification failed: ' . $e->getMessage(),
                processorName:     $this->getName(),
            );
        }
    }

    public function isSandbox(): bool
    {
        return $this->sandbox;
    }

    public function getName(): string
    {
        return 'Paddle' . ($this->sandbox ? ' (Sandbox)' : '');
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Paddle-specific methods (used by OrderReview / checkout blade)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * The client-side token sent to the browser to initialise Paddle.js.
     */
    public function getClientToken(): string
    {
        return $this->sandbox
            ? (config('services.paddle.sandbox_client_token') ?? '')
            : (config('services.paddle.client_token') ?? '');
    }

    /**
     * The environment string Paddle.js expects: 'sandbox' or 'production'.
     */
    public function getEnvironment(): string
    {
        return $this->sandbox ? 'sandbox' : 'production';
    }

    /**
     * Create a Paddle Billing transaction and return its ID.
     * The transaction_id is passed to Paddle.js to open the inline checkout.
     *
     * Called server-side in OrderReview::preparePayment().
     *
     * @param  float  $amount   Order total in major currency units (e.g. 29.99)
     * @param  string $currency ISO 4217 currency code (e.g. 'USD', 'GBP')
     * @param  array  $meta     Optional: customer_email, order_ref, paddle_price_id, order_description
     */
    public function createTransaction(float $amount, string $currency = 'USD', array $meta = []): array
    {
        try {
            $paddle = $this->client();

            $customData = array_filter([
                'order_ref'      => $meta['order_ref']      ?? null,
                'customer_email' => $meta['customer_email'] ?? null,
            ]);

            $items = [];

            if (!empty($meta['cart_items'])) {
                $cartItems       = $meta['cart_items'];
                $subtotal        = $meta['subtotal'] ?? 0;
                $discountAmount  = $meta['discount_amount'] ?? 0;
                $vatInclusive    = $meta['vat_inclusive'] ?? false;
                $crossBorder     = $meta['cross_border'] ?? false;
                $customerCountry = $meta['customer_country'] ?? 'US';

                foreach ($cartItems as $cartItem) {
                    if (empty($cartItem->variant_id)) {
                        continue;
                    }
                    $variant = ProductVariant::find($cartItem->variant_id);
                    if (!$variant) {
                        continue;
                    }

                    $paddlePriceId = $this->sandbox
                        ? ($variant->paddle_sandbox_price_id ?? null)
                        : ($variant->paddle_live_price_id    ?? null);

                    // Final price of item (after item-level and order-level discounts)
                    $finalUnitPrice = (float) $cartItem->item_price;
                    $discountText = '';
                    if ($subtotal > 0 && $discountAmount > 0) {
                        $ratio = 1 - ($discountAmount / $subtotal);
                        $finalUnitPrice = $finalUnitPrice * $ratio;
                        
                        $itemDiscount = (float) $cartItem->item_price * ($discountAmount / $subtotal);
                        $discountText = "Order Discount Applied: -$" . number_format($itemDiscount, 2);
                    }

                    if ($vatInclusive && $crossBorder) {
                        $finalUnitPrice = \App\Services\TaxCalculationService::adjustSubtotalForVat($finalUnitPrice, $customerCountry);
                    }

                    $quantity = (int) $cartItem->item_qty;

                    // 1. If pre-configured Paddle price ID exists AND final price exactly matches paddle_price
                    if (!empty($paddlePriceId) && $variant->paddle_price !== null && (float) $finalUnitPrice === (float) $variant->paddle_price) {
                        $items[] = new \Paddle\SDK\Resources\Transactions\Operations\Create\TransactionCreateItem(
                            priceId: $paddlePriceId,
                            quantity: $quantity
                        );
                    } else {
                        // 2. Dynamically create a "non-catalog" item
                        $amountInCents = (string) (int) round($finalUnitPrice * 100);
                        $currencyCode = $variant->paddle_currency_code ?: 'USD';
                        $money = new \Paddle\SDK\Entities\Shared\Money(
                            $amountInCents,
                            \Paddle\SDK\Entities\Shared\CurrencyCode::from(strtoupper($currencyCode))
                        );

                        $billingCycle = null;
                        if (!empty($variant->paddle_interval)) {
                            $billingCycle = new \Paddle\SDK\Entities\Shared\TimePeriod(
                                \Paddle\SDK\Entities\Shared\Interval::from(strtolower($variant->paddle_interval)),
                                (int) ($variant->paddle_frequency ?: 1)
                            );
                        }

                        $description = $variant->product->title;
                        if ($variant->sku) {
                            $description .= ' (' . $variant->sku . ')';
                        }
                        if ($discountText) {
                            $description .= ' [' . $discountText . ']';
                        }

                        // Try to fetch existing product ID if price ID is set
                        $productId = null;
                        if (!empty($paddlePriceId)) {
                            try {
                                $priceObj = $paddle->prices->get($paddlePriceId);
                                $productId = $priceObj->productId;
                            } catch (\Throwable $e) {
                                \Illuminate\Support\Facades\Log::warning("Could not fetch Paddle price for ID {$paddlePriceId}: " . $e->getMessage());
                            }
                        }

                        if ($productId) {
                            // Non-catalog price for existing catalog product
                            $priceObject = new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogPrice(
                                description: $description,
                                unitPrice: $money,
                                productId: $productId,
                                billingCycle: $billingCycle
                            );
                        } else {
                            // Non-catalog price and product
                            $priceObject = new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogPriceWithProduct(
                                description: $description,
                                unitPrice: $money,
                                product: new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogProduct(
                                    name: $variant->product->title,
                                    taxCategory: \Paddle\SDK\Entities\Shared\TaxCategory::Standard()
                                ),
                                billingCycle: $billingCycle
                            );
                        }

                        $items[] = new \Paddle\SDK\Resources\Transactions\Operations\Create\TransactionCreateItemWithPrice(
                            price: $priceObject,
                            quantity: $quantity
                        );
                    }
                }

                // Add shipping as a separate line item if > 0
                if (!empty($meta['shipping_fee']) && (float) $meta['shipping_fee'] > 0) {
                    $shippingCents = (string) (int) round($meta['shipping_fee'] * 100);
                    $items[] = new \Paddle\SDK\Resources\Transactions\Operations\Create\TransactionCreateItemWithPrice(
                        price: new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogPriceWithProduct(
                            description: 'Shipping & Delivery',
                            unitPrice: new \Paddle\SDK\Entities\Shared\Money(
                                $shippingCents,
                                \Paddle\SDK\Entities\Shared\CurrencyCode::from(strtoupper($currency))
                            ),
                            product: new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogProduct(
                                name: 'Shipping Charges',
                                taxCategory: \Paddle\SDK\Entities\Shared\TaxCategory::Standard()
                            )
                        ),
                        quantity: 1
                    );
                }

                // Add handling surcharge as a separate line item if > 0
                if (!empty($meta['handling_fee']) && (float) $meta['handling_fee'] > 0) {
                    $handlingCents = (string) (int) round($meta['handling_fee'] * 100);
                    $items[] = new \Paddle\SDK\Resources\Transactions\Operations\Create\TransactionCreateItemWithPrice(
                        price: new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogPriceWithProduct(
                            description: 'Handling Surcharge',
                            unitPrice: new \Paddle\SDK\Entities\Shared\Money(
                                $handlingCents,
                                \Paddle\SDK\Entities\Shared\CurrencyCode::from(strtoupper($currency))
                            ),
                            product: new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogProduct(
                                name: 'Handling Charges',
                                taxCategory: \Paddle\SDK\Entities\Shared\TaxCategory::Standard()
                            )
                        ),
                        quantity: 1
                    );
                }
            }

            // Fallback to legacy single item logic if items array is empty (for backward compatibility)
            if (empty($items)) {
                if (!empty($meta['paddle_price_id'])) {
                    $items[] = new \Paddle\SDK\Resources\Transactions\Operations\Create\TransactionCreateItem(
                        priceId:  $meta['paddle_price_id'],
                        quantity: 1,
                    );
                } else {
                    $amountInCents = (string) (int) round($amount * 100);
                    $items[] = new \Paddle\SDK\Resources\Transactions\Operations\Create\TransactionCreateItemWithPrice(
                        price: new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogPriceWithProduct(
                            description: $meta['order_description'] ?? 'Store Order',
                            unitPrice: new \Paddle\SDK\Entities\Shared\Money(
                                $amountInCents,
                                \Paddle\SDK\Entities\Shared\CurrencyCode::from(strtoupper($currency))
                            ),
                            product: new \Paddle\SDK\Resources\Transactions\Operations\Price\TransactionNonCatalogProduct(
                                name: 'Store Order',
                                taxCategory: \Paddle\SDK\Entities\Shared\TaxCategory::Standard()
                            )
                        ),
                        quantity: 1,
                    );
                }
            }

            $transaction = $paddle->transactions->create(
                new \Paddle\SDK\Resources\Transactions\Operations\CreateTransaction(
                    items: $items,
                    customData: $customData ? new \Paddle\SDK\Entities\Shared\CustomData($customData) : null,
                )
            );

            return [
                'transaction_id' => $transaction->id,
                'environment'    => $this->getEnvironment(),
                'client_token'   => $this->getClientToken(),
            ];

        } catch (\Paddle\SDK\Exceptions\ApiError $e) {
            throw new \RuntimeException('Paddle transaction creation failed: ' . $e->getMessage(), 0, $e);
        }
    }

    /**
     * Cancel a recurring Paddle subscription.
     *
     * Automatically resolves sub_ IDs directly, or queries transactions (txn_)
     * and customers (ctm_) to retrieve the linked subscription ID.
     *
     * @throws \Throwable
     */
    public function cancelSubscription(string $subscriptionId, string $effectiveFrom = 'immediately'): bool
    {
        if (empty($subscriptionId)) {
            throw new \InvalidArgumentException('Paddle subscription ID cannot be empty.');
        }

        $apiKey = $this->sandbox
            ? (config('services.paddle.sandbox_api_key') ?? '')
            : (config('services.paddle.api_key') ?? '');

        // Fallback to whichever key is present if primary is empty
        if (empty($apiKey)) {
            $apiKey = config('services.paddle.sandbox_api_key') ?: config('services.paddle.api_key') ?: env('PADDLE_API_KEY') ?: env('PADDLE_SANDBOX_API_KEY');
        }

        $baseUrl = $this->sandbox ? 'https://sandbox-api.paddle.com' : 'https://api.paddle.com';
        $targetSubId = trim($subscriptionId);

        // If a Transaction ID (txn_...) was passed instead of sub_...
        if (str_starts_with($targetSubId, 'txn_')) {
            try {
                $txnRes = \Illuminate\Support\Facades\Http::withToken($apiKey)->get("{$baseUrl}/transactions/{$targetSubId}");
                if ($txnRes->successful()) {
                    $foundSubId = $txnRes->json('data.subscription_id');
                    if (!empty($foundSubId)) {
                        $targetSubId = $foundSubId;
                    } else {
                        $customerId = $txnRes->json('data.customer_id');
                        if (!empty($customerId)) {
                            $subsRes = \Illuminate\Support\Facades\Http::withToken($apiKey)->get("{$baseUrl}/subscriptions", [
                                'customer_id' => $customerId,
                                'status'      => 'active',
                            ]);
                            if ($subsRes->successful() && !empty($subsRes->json('data.0.id'))) {
                                $targetSubId = $subsRes->json('data.0.id');
                            }
                        }
                    }
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning("[PaddleProcessor] Could not resolve subscription from transaction {$targetSubId}: " . $e->getMessage());
            }
        }

        // If a Customer ID (ctm_...) was passed
        if (str_starts_with($targetSubId, 'ctm_')) {
            try {
                $subsRes = \Illuminate\Support\Facades\Http::withToken($apiKey)->get("{$baseUrl}/subscriptions", [
                    'customer_id' => $targetSubId,
                    'status'      => 'active',
                ]);
                if ($subsRes->successful() && !empty($subsRes->json('data.0.id'))) {
                    $targetSubId = $subsRes->json('data.0.id');
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning("[PaddleProcessor] Could not resolve subscription from customer {$targetSubId}: " . $e->getMessage());
            }
        }

        $response = \Illuminate\Support\Facades\Http::withToken($apiKey)
            ->withHeaders(['Content-Type' => 'application/json'])
            ->post("{$baseUrl}/subscriptions/{$targetSubId}/cancel", [
                'effective_from' => $effectiveFrom,
            ]);

        // If sandbox failed with invalid_url or not found, try the alternate environment if configured
        if ($response->failed() && $response->status() === 404 && $this->sandbox) {
            $liveKey = config('services.paddle.api_key') ?? '';
            if (!empty($liveKey)) {
                $response = \Illuminate\Support\Facades\Http::withToken($liveKey)
                    ->withHeaders(['Content-Type' => 'application/json'])
                    ->post("https://api.paddle.com/subscriptions/{$targetSubId}/cancel", [
                        'effective_from' => $effectiveFrom,
                    ]);
            }
        }

        if ($response->failed()) {
            \Illuminate\Support\Facades\Log::error("Paddle cancelSubscription failed for {$targetSubId} (input was {$subscriptionId}): " . $response->body());
            throw new \RuntimeException('Paddle subscription cancellation failed: ' . $response->body());
        }

        return true;
    }

    /**
     * Process a partial or full refund with Paddle Billing.
     *
     * @param  string      $transactionId Paddle Transaction ID (txn_...) or Subscription ID (sub_...)
     * @param  float       $amount        Refund amount in major currency units (e.g. 25.50)
     * @param  string|null $reason        Optional admin reason/note
     * @param  string      $currency      ISO 4217 currency code (default 'USD')
     */
    public function refund(string $transactionId, float $amount, ?string $reason = null, string $currency = 'USD'): PaymentResult
    {
        $transactionId = trim($transactionId);
        if (empty($transactionId)) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'No Paddle transaction ID provided for refund.',
                processorName:     $this->getName(),
            );
        }

        $apiKey = $this->sandbox
            ? (config('services.paddle.sandbox_api_key') ?? '')
            : (config('services.paddle.api_key') ?? '');

        if (empty($apiKey)) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'Paddle API Key is missing in environment.',
                processorName:     $this->getName(),
            );
        }

        $baseUrl = $this->sandbox
            ? 'https://sandbox-api.paddle.com'
            : 'https://api.paddle.com';

        try {
            $targetTxnId = $transactionId;

            // If a Subscription ID or Customer ID was passed, find the most recent completed transaction
            if (str_starts_with($targetTxnId, 'sub_')) {
                $txnsRes = \Illuminate\Support\Facades\Http::withToken($apiKey)->get("{$baseUrl}/transactions", [
                    'subscription_id' => $targetTxnId,
                    'status'          => 'completed',
                    'per_page'        => 1,
                ]);
                if ($txnsRes->successful() && !empty($txnsRes->json('data.0.id'))) {
                    $targetTxnId = $txnsRes->json('data.0.id');
                }
            } elseif (str_starts_with($targetTxnId, 'ctm_')) {
                $txnsRes = \Illuminate\Support\Facades\Http::withToken($apiKey)->get("{$baseUrl}/transactions", [
                    'customer_id' => $targetTxnId,
                    'status'      => 'completed',
                    'per_page'    => 1,
                ]);
                if ($txnsRes->successful() && !empty($txnsRes->json('data.0.id'))) {
                    $targetTxnId = $txnsRes->json('data.0.id');
                }
            }

            // Fetch the transaction details to get line items and currency
            $txnRes = \Illuminate\Support\Facades\Http::withToken($apiKey)->get("{$baseUrl}/transactions/{$targetTxnId}");
            $txnData = $txnRes->json('data');

            $items = [];
            $adjustmentType = 'full';

            if ($txnRes->successful() && !empty($txnData['details']['line_items'])) {
                $lineItems = $txnData['details']['line_items'];
                $totalTxnAmount = (float) ($txnData['details']['totals']['total'] ?? 0) / 100;

                // If refund amount is less than total, make it partial
                if ($totalTxnAmount > 0 && abs($amount - $totalTxnAmount) > 0.01) {
                    $adjustmentType = 'partial';
                    $firstItemId = $lineItems[0]['id'] ?? null;
                    if ($firstItemId) {
                        $items[] = [
                            'item_id' => $firstItemId,
                            'type'    => 'partial',
                            'amount'  => (string) number_format($amount, 2, '.', ''),
                        ];
                    }
                }
            }

            $payload = [
                'action'         => 'refund',
                'transaction_id' => $targetTxnId,
                'reason'         => $reason ?: 'General customer refund',
                'type'           => $adjustmentType,
            ];

            if (!empty($items)) {
                $payload['items'] = $items;
            }

            $response = \Illuminate\Support\Facades\Http::withToken($apiKey)
                ->withHeaders(['Content-Type' => 'application/json'])
                ->post("{$baseUrl}/adjustments", $payload);

            if ($response->failed()) {
                $errBody = $response->json();
                $detail = $errBody['error']['detail'] ?? $response->body();
                \Illuminate\Support\Facades\Log::error("Paddle refund failed for {$targetTxnId}: " . $response->body());
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    errorMessage:      'Paddle Refund Error: ' . $detail,
                    processorName:     $this->getName(),
                );
            }

            $adjData = $response->json('data');
            $adjId = $adjData['id'] ?? ('adj_' . \Illuminate\Support\Str::random(16));

            return new PaymentResult(
                success:           true,
                authorizationCode: $adjId,
                transactionId:     $adjId,
                processorName:     $this->getName(),
            );

        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error("Paddle refund exception for {$transactionId}: " . $e->getMessage());
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'Paddle Refund Failed: ' . $e->getMessage(),
                processorName:     $this->getName(),
            );
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Protected helpers (overridable in extension class)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Returns a configured Paddle SDK Client.
     *
     * Made protected so extension classes can override the client
     * (e.g., to inject custom middleware or retry logic).
     *
     * @throws \RuntimeException if SDK is missing or .env key is not set
     */
    protected function client(): \Paddle\SDK\Client
    {
        if (!class_exists(\Paddle\SDK\Client::class)) {
            throw new \RuntimeException(
                'The Paddle SDK is not installed. Run: composer require paddlehq/paddle-php-sdk'
            );
        }

        $apiKey = $this->sandbox
            ? (config('services.paddle.sandbox_api_key') ?? '')
            : (config('services.paddle.api_key') ?? '');

        if (empty($apiKey)) {
            throw new \RuntimeException(
                $this->sandbox
                    ? 'PADDLE_SANDBOX_API_KEY is not set in .env'
                    : 'PADDLE_API_KEY is not set in .env'
            );
        }

        return new \Paddle\SDK\Client(
            apiKey:  $apiKey,
            options: new \Paddle\SDK\Options(
                environment: $this->sandbox ? \Paddle\SDK\Environment::SANDBOX : \Paddle\SDK\Environment::PRODUCTION
            ),
        );
    }
}
