<?php

namespace App\Services\Payments\Processors;

use App\Services\Payments\Contracts\PaymentProcessorInterface;
use App\Services\Payments\PaymentResult;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * PayPalProcessor — built-in PayPal Expanded Checkout payment processor driver.
 *
 * This class is always available as a default processor (processor_id = 3).
 * It is PSR-4 autoloaded from app/Services/Payments/Processors/.
 *
 * CUSTOMISATION
 * ─────────────
 * Do NOT edit this file directly — it may be overwritten by platform updates.
 * To extend or override behaviour, create:
 *
 *   payment-processors/paypal/PayPalProcessorExtension.php
 *
 * If that file exists, it is loaded automatically and used in place of this
 * class for processor_id = 3. See payment-processors/paypal/README.md for
 * a full extension template.
 *
 * CREDENTIALS
 * ───────────
 * Add to .env (sandbox and/or production):
 *
 *   PAYPAL_CLIENT_ID=your_live_client_id
 *   PAYPAL_CLIENT_SECRET=your_live_client_secret
 *   PAYPAL_SANDBOX_CLIENT_ID=your_sandbox_client_id
 *   PAYPAL_SANDBOX_CLIENT_SECRET=your_sandbox_client_secret
 */
class PayPalProcessor implements PaymentProcessorInterface
{
    public function __construct(private readonly bool $sandbox = false) {}

    // ─────────────────────────────────────────────────────────────────────────
    // PaymentProcessorInterface implementation
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Finalize / capture a PayPal payment after the client-side PayPal SDK has
     * approved the order.
     *
     * $payload carries:
     *   - ['order_id' => 'order_xxxx']
     */
    public function charge(float $amount, string $currency, array $payload): PaymentResult
    {
        // ── Subscription verification flow ──────────────────────────────────
        $subscriptionId = $payload['subscription_id'] ?? null;
        if (empty($subscriptionId) && !empty($payload['order_id']) && str_starts_with($payload['order_id'], 'I-')) {
            $subscriptionId = $payload['order_id'];
        }

        if (!empty($subscriptionId)) {
            try {
                $subData = $this->getSubscription($subscriptionId);
                $status = strtoupper($subData['status'] ?? '');

                if (!in_array($status, ['ACTIVE', 'APPROVED'])) {
                    return new PaymentResult(
                        success:           false,
                        authorizationCode: '',
                        errorMessage:      "PayPal Subscription status: $status",
                        processorName:     $this->getName(),
                    );
                }

                return new PaymentResult(
                    success:           true,
                    authorizationCode: $subscriptionId,
                    transactionId:     $subscriptionId,
                    processorName:     $this->getName(),
                );
            } catch (\Throwable $e) {
                Log::error('PayPal subscription verification error: ' . $e->getMessage());
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    errorMessage:      'PayPal subscription verification failed: ' . $e->getMessage(),
                    processorName:     $this->getName(),
                );
            }
        }

        // ── Standard one-time order capture flow ────────────────────────────
        $orderId = $payload['order_id'] ?? null;

        if (empty($orderId)) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'No PayPal order ID received.',
                processorName:     $this->getName(),
            );
        }

        try {
            $accessToken = $this->getAccessToken();
            $baseUrl = $this->getBaseUrl();

            // Capture the order
            $response = Http::withToken($accessToken)
                ->withHeaders([
                    'PayPal-Request-Id' => uniqid(),
                    'Content-Type' => 'application/json',
                ])
                ->post("$baseUrl/v2/checkout/orders/$orderId/capture", new \stdClass());

            if ($response->failed()) {
                // If it failed, let's verify if it was ALREADY captured (e.g. via double submit or webhook)
                $check = Http::withToken($accessToken)->get("$baseUrl/v2/checkout/orders/$orderId");
                if ($check->successful()) {
                    $orderData = $check->json();
                    if (($orderData['status'] ?? '') === 'COMPLETED') {
                        $captureId = $orderData['purchase_units'][0]['payments']['captures'][0]['id'] ?? $orderId;
                        return new PaymentResult(
                            success:           true,
                            authorizationCode: $captureId,
                            transactionId:     $orderId,
                            processorName:     $this->getName(),
                        );
                    }
                }

                $err = $response->json();
                $message = $err['message'] ?? $err['error_description'] ?? 'Capture failed.';
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    errorMessage:      "PayPal API Error: $message",
                    processorName:     $this->getName(),
                );
            }

            $data = $response->json();
            if (($data['status'] ?? '') !== 'COMPLETED') {
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    errorMessage:      'PayPal Order status: ' . ($data['status'] ?? 'unknown'),
                    processorName:     $this->getName(),
                );
            }

            $captureId = $data['purchase_units'][0]['payments']['captures'][0]['id'] ?? $orderId;

            return new PaymentResult(
                success:           true,
                authorizationCode: $captureId,
                transactionId:     $orderId,
                processorName:     $this->getName(),
            );

        } catch (\Throwable $e) {
            Log::error('PayPal capture error: ' . $e->getMessage());
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'PayPal verification failed: ' . $e->getMessage(),
                processorName:     $this->getName(),
            );
        }
    }

    /**
     * Retrieve subscription details from PayPal.
     */
    public function getSubscription(string $subscriptionId): array
    {
        $accessToken = $this->getAccessToken();
        $baseUrl = $this->getBaseUrl();

        $response = Http::withToken($accessToken)
            ->withHeaders(['Content-Type' => 'application/json'])
            ->get("$baseUrl/v1/billing/subscriptions/$subscriptionId");

        if ($response->failed()) {
            $err = $response->json();
            $msg = $err['message'] ?? 'Could not retrieve PayPal subscription.';
            throw new \RuntimeException($msg);
        }

        return $response->json();
    }

    /**
     * Create a PayPal order on the server side and return its ID.
     */
    public function createOrder(float $amount, string $currency): string
    {
        $accessToken = $this->getAccessToken();
        $baseUrl = $this->getBaseUrl();

        $response = Http::withToken($accessToken)
            ->withHeaders(['Content-Type' => 'application/json'])
            ->post("$baseUrl/v2/checkout/orders", [
                'intent' => 'CAPTURE',
                'purchase_units' => [
                    [
                        'amount' => [
                            'currency_code' => strtoupper($currency),
                            'value' => number_format($amount, 2, '.', ''),
                        ]
                    ]
                ]
            ]);

        if ($response->failed()) {
            $err = $response->json();
            $msg = $err['message'] ?? 'Could not create PayPal order.';
            throw new \RuntimeException($msg);
        }

        return $response->json()['id'];
    }

    /**
     * Create a Catalog Product in PayPal (POST /v1/catalogs/products).
     */
    public function createCatalogProduct(string $name, string $description = '', string $type = 'SERVICE', string $category = 'SOFTWARE', ?bool $forceSandbox = null): string
    {
        $accessToken = $this->getAccessToken($forceSandbox);
        $baseUrl = $this->getBaseUrl($forceSandbox);

        $payload = [
            'name'        => mb_substr($name, 0, 127),
            'description' => mb_substr($description ?: $name, 0, 256),
            'type'        => in_array(strtoupper($type), ['PHYSICAL', 'DIGITAL', 'SERVICE']) ? strtoupper($type) : 'SERVICE',
            'category'    => $category ?: 'SOFTWARE',
        ];

        $response = Http::withToken($accessToken)
            ->withHeaders(['Content-Type' => 'application/json'])
            ->post("$baseUrl/v1/catalogs/products", $payload);

        if ($response->failed()) {
            $err = $response->json();
            $msg = $err['message'] ?? 'Could not create PayPal Catalog Product.';
            if (!empty($err['details']) && is_array($err['details'])) {
                $msg .= ' Details: ' . json_encode($err['details']);
            }
            throw new \RuntimeException($msg);
        }

        return $response->json()['id'];
    }

    /**
     * Create a Billing Plan in PayPal (POST /v1/billing/plans).
     */
    public function createBillingPlan(array $params, ?bool $forceSandbox = null): string
    {
        $accessToken = $this->getAccessToken($forceSandbox);
        $baseUrl = $this->getBaseUrl($forceSandbox);

        $productId    = $params['product_id'];
        $name         = $params['name'] ?? 'Subscription Plan';
        $description  = $params['description'] ?? 'Recurring subscription plan';
        $price        = (float) ($params['price'] ?? 0.00);
        $currency     = strtoupper($params['currency'] ?? 'USD');
        $intervalUnit = strtoupper($params['interval'] ?? 'MONTH');
        $frequency    = (int) ($params['frequency'] ?? 1);
        $totalCycles  = (int) ($params['total_cycles'] ?? 0);
        $trialEnabled = !empty($params['trial_enabled']);
        $trialDays    = (int) ($params['trial_days'] ?? 0);
        $trialPrice   = (float) ($params['trial_price'] ?? 0.00);

        if (!in_array($intervalUnit, ['DAY', 'WEEK', 'MONTH', 'YEAR'])) {
            $intervalUnit = 'MONTH';
        }
        if ($frequency < 1) {
            $frequency = 1;
        }

        $billingCycles = [];
        $sequence = 1;

        if ($trialEnabled && $trialDays > 0) {
            $billingCycles[] = [
                'frequency' => [
                    'interval_unit'  => 'DAY',
                    'interval_count' => $trialDays,
                ],
                'tenure_type'    => 'TRIAL',
                'sequence'       => $sequence++,
                'total_cycles'   => 1,
                'pricing_scheme' => [
                    'fixed_price' => [
                        'value'         => number_format($trialPrice, 2, '.', ''),
                        'currency_code' => $currency,
                    ],
                ],
            ];
        }

        $billingCycles[] = [
            'frequency' => [
                'interval_unit'  => $intervalUnit,
                'interval_count' => $frequency,
            ],
            'tenure_type'    => 'REGULAR',
            'sequence'       => $sequence,
            'total_cycles'   => $totalCycles,
            'pricing_scheme' => [
                'fixed_price' => [
                    'value'         => number_format($price, 2, '.', ''),
                    'currency_code' => $currency,
                ],
            ],
        ];

        $payload = [
            'product_id'          => $productId,
            'name'                => mb_substr($name, 0, 127),
            'description'         => mb_substr($description, 0, 127),
            'billing_cycles'      => $billingCycles,
            'payment_preferences' => [
                'auto_bill_outstanding'     => true,
                'setup_fee_failure_action' => 'CONTINUE',
                'payment_failure_threshold' => 3,
            ],
        ];

        $response = Http::withToken($accessToken)
            ->withHeaders(['Content-Type' => 'application/json'])
            ->post("$baseUrl/v1/billing/plans", $payload);

        if ($response->failed()) {
            $err = $response->json();
            $msg = $err['message'] ?? 'Could not create PayPal Billing Plan.';
            if (!empty($err['details']) && is_array($err['details'])) {
                $msg .= ' Details: ' . json_encode($err['details']);
            }
            throw new \RuntimeException($msg);
        }

        return $response->json()['id'];
    }

    /**
     * Create both Product and Plan on-the-fly via PayPal API.
     */
    public function createPlanOnTheFly(array $params, ?bool $forceSandbox = null): array
    {
        $productName = $params['product_name'] ?? $params['name'] ?? 'Subscription Product';
        $productDesc = $params['product_description'] ?? 'Subscription service';
        $type        = $params['product_type'] ?? 'SERVICE';

        $productId = $this->createCatalogProduct($productName, $productDesc, $type, 'SOFTWARE', $forceSandbox);

        $planParams = array_merge($params, [
            'product_id' => $productId,
        ]);

        $planId = $this->createBillingPlan($planParams, $forceSandbox);

        return [
            'product_id' => $productId,
            'plan_id'    => $planId,
        ];
    }

    public function getClientId(?bool $forceSandbox = null): string
    {
        $isSandbox = $forceSandbox !== null ? $forceSandbox : $this->sandbox;
        return $isSandbox
            ? config('services.paypal.sandbox_client_id') ?? env('PAYPAL_SANDBOX_CLIENT_ID', '')
            : config('services.paypal.client_id') ?? env('PAYPAL_CLIENT_ID', '');
    }

    private function getClientSecret(?bool $forceSandbox = null): string
    {
        $isSandbox = $forceSandbox !== null ? $forceSandbox : $this->sandbox;
        return $isSandbox
            ? config('services.paypal.sandbox_client_secret') ?? env('PAYPAL_SANDBOX_CLIENT_SECRET', '')
            : config('services.paypal.client_secret') ?? env('PAYPAL_CLIENT_SECRET', '');
    }

    public function getBaseUrl(?bool $forceSandbox = null): string
    {
        $isSandbox = $forceSandbox !== null ? $forceSandbox : $this->sandbox;
        return $isSandbox ? 'https://api-m.sandbox.paypal.com' : 'https://api-m.paypal.com';
    }

    public function getAccessToken(?bool $forceSandbox = null): string
    {
        $clientId = $this->getClientId($forceSandbox);
        $clientSecret = $this->getClientSecret($forceSandbox);
        $baseUrl = $this->getBaseUrl($forceSandbox);

        if (empty($clientId) || empty($clientSecret)) {
            $envName = ($forceSandbox !== null ? $forceSandbox : $this->sandbox) ? 'Sandbox' : 'Live';
            throw new \RuntimeException("PayPal {$envName} credentials are not configured in the environment.");
        }

        $response = Http::withBasicAuth($clientId, $clientSecret)
            ->asForm()
            ->post("$baseUrl/v1/oauth2/token", [
                'grant_type' => 'client_credentials'
            ]);

        if ($response->failed()) {
            throw new \RuntimeException('Failed to authenticate with PayPal. Check client ID and secret.');
        }

        return $response->json()['access_token'];
    }

    public function cancelSubscription(string $subscriptionId, string $reason = 'Cancelled by customer', ?bool $forceSandbox = null): bool
    {
        if (empty($subscriptionId)) {
            throw new \InvalidArgumentException('PayPal subscription ID cannot be empty.');
        }

        $accessToken = $this->getAccessToken($forceSandbox);
        $baseUrl = $this->getBaseUrl($forceSandbox);

        $response = Http::withToken($accessToken)
            ->withHeaders(['Content-Type' => 'application/json'])
            ->post("{$baseUrl}/v1/billing/subscriptions/{$subscriptionId}/cancel", [
                'reason' => $reason,
            ]);

        // PayPal returns HTTP 204 No Content on successful cancellation
        if ($response->failed() && $response->status() !== 204) {
            \Illuminate\Support\Facades\Log::error("PayPal cancelSubscription failed for {$subscriptionId}: " . $response->body());
            throw new \RuntimeException('PayPal subscription cancellation failed: ' . $response->body());
        }

        return true;
    }

    public function isSandbox(): bool
    {
        return $this->sandbox;
    }

    public function getName(): string
    {
        return 'PayPal Payments';
    }

    /**
     * Process a partial or full refund with PayPal.
     *
     * @param  string      $transactionId PayPal Capture ID, Order ID, or Subscription ID (I-...)
     * @param  float       $amount        Refund amount in major currency units (e.g. 25.50)
     * @param  string|null $reason        Optional admin reason/note
     * @param  string      $currency      ISO 4217 currency code (default 'USD')
     */
    public function refund(string $transactionId, float $amount, ?string $reason = null, string $currency = 'USD'): PaymentResult
    {
        $transactionId = trim($transactionId);
        if (empty($transactionId)) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'No PayPal capture ID or order ID provided for refund.',
                processorName:     $this->getName(),
            );
        }

        try {
            $accessToken = $this->getAccessToken();
            $baseUrl     = $this->getBaseUrl();
            $targetCaptureId = $transactionId;
            $isSubscriptionTxn = false;

            // If a Subscription ID (I-...) was passed, find the latest transaction
            if (str_starts_with($targetCaptureId, 'I-')) {
                $isSubscriptionTxn = true;
                $startTime = now()->subYears(2)->format('Y-m-d\TH:i:s\Z');
                $endTime   = now()->addDay()->format('Y-m-d\TH:i:s\Z');
                $subRes = Http::withToken($accessToken)
                    ->get("{$baseUrl}/v1/billing/subscriptions/{$targetCaptureId}/transactions", [
                        'start_time' => $startTime,
                        'end_time'   => $endTime,
                    ]);
                if ($subRes->successful() && !empty($subRes->json('transactions.0.id'))) {
                    $targetCaptureId = $subRes->json('transactions.0.id');
                }
            }

            // If an Order ID was passed instead of capture ID, retrieve the order to get the capture ID
            if (!str_starts_with($targetCaptureId, 'I-') && strlen($targetCaptureId) <= 20 && !str_starts_with($targetCaptureId, 'CAPTURE-')) {
                try {
                    $orderCheck = Http::withToken($accessToken)->get("{$baseUrl}/v2/checkout/orders/{$targetCaptureId}");
                    if ($orderCheck->successful()) {
                        $orderData = $orderCheck->json();
                        $resolvedCapture = $orderData['purchase_units'][0]['payments']['captures'][0]['id'] ?? null;
                        if ($resolvedCapture) {
                            $targetCaptureId = $resolvedCapture;
                        }
                    }
                } catch (\Throwable $e) {
                    \Illuminate\Support\Facades\Log::warning("[PayPalProcessor] Order lookup skipped for {$targetCaptureId}: " . $e->getMessage());
                }
            }

            $payload = [
                'amount' => [
                    'value'         => number_format($amount, 2, '.', ''),
                    'currency_code' => strtoupper($currency ?: 'USD'),
                ],
            ];
            if (!empty($reason)) {
                $payload['note_to_payer'] = $reason;
            }

            // Primary: Attempt refund via PayPal Captures API v2
            $response = Http::withToken($accessToken)
                ->withHeaders([
                    'PayPal-Request-Id' => uniqid('rfnd_', true),
                    'Content-Type'      => 'application/json',
                ])
                ->post("{$baseUrl}/v2/payments/captures/{$targetCaptureId}/refund", $payload);

            // Fallback for subscription sale transactions if v2 capture returned 404 or unprocessable
            if ($response->failed() && ($isSubscriptionTxn || str_starts_with($targetCaptureId, 'SALE-') || $response->status() === 404)) {
                $salePayload = [
                    'amount' => [
                        'total'    => number_format($amount, 2, '.', ''),
                        'currency' => strtoupper($currency ?: 'USD'),
                    ],
                ];
                if (!empty($reason)) {
                    $salePayload['description'] = $reason;
                }

                $saleResponse = Http::withToken($accessToken)
                    ->withHeaders(['Content-Type' => 'application/json'])
                    ->post("{$baseUrl}/v1/payments/sale/{$targetCaptureId}/refund", $salePayload);

                if ($saleResponse->successful()) {
                    $saleData = $saleResponse->json();
                    $refundId = $saleData['id'] ?? ('PAYPAL-RFND-' . strtoupper(\Illuminate\Support\Str::random(8)));
                    return new PaymentResult(
                        success:           true,
                        authorizationCode: $refundId,
                        transactionId:     $refundId,
                        processorName:     $this->getName(),
                    );
                }
            }

            if ($response->failed()) {
                $err = $response->json() ?? [];
                $detailMsgs = [];
                if (!empty($err['details']) && is_array($err['details'])) {
                    foreach ($err['details'] as $detail) {
                        $desc = $detail['description'] ?? $detail['issue'] ?? null;
                        if ($desc) {
                            $detailMsgs[] = $desc;
                        }
                    }
                }
                $errorMessage = !empty($detailMsgs)
                    ? implode('; ', $detailMsgs)
                    : ($err['message'] ?? $err['error_description'] ?? $response->body());

                \Illuminate\Support\Facades\Log::error("PayPal refund failed for capture {$targetCaptureId}: " . $response->body());
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    errorMessage:      'PayPal Refund Error: ' . $errorMessage,
                    processorName:     $this->getName(),
                );
            }

            $data = $response->json();
            $refundId = $data['id'] ?? ('PAYPAL-RFND-' . strtoupper(\Illuminate\Support\Str::random(8)));

            return new PaymentResult(
                success:           true,
                authorizationCode: $refundId,
                transactionId:     $refundId,
                processorName:     $this->getName(),
            );

        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error("PayPal refund exception for {$transactionId}: " . $e->getMessage());
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'PayPal Refund Failed: ' . $e->getMessage(),
                processorName:     $this->getName(),
            );
        }
    }
}
