<?php

namespace App\Services\Payments\Processors;

use App\Services\Payments\Contracts\PaymentProcessorInterface;
use App\Services\Payments\PaymentResult;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * PayPalProcessor — built-in PayPal Expanded Checkout payment processor driver.
 *
 * This class is always available as a default processor (processor_id = 3).
 * It is PSR-4 autoloaded from app/Services/Payments/Processors/.
 *
 * CUSTOMISATION
 * ─────────────
 * Do NOT edit this file directly — it may be overwritten by platform updates.
 * To extend or override behaviour, create:
 *
 *   payment-processors/paypal/PayPalProcessorExtension.php
 *
 * If that file exists, it is loaded automatically and used in place of this
 * class for processor_id = 3. See payment-processors/paypal/README.md for
 * a full extension template.
 *
 * CREDENTIALS
 * ───────────
 * Add to .env (sandbox and/or production):
 *
 *   PAYPAL_CLIENT_ID=your_live_client_id
 *   PAYPAL_CLIENT_SECRET=your_live_client_secret
 *   PAYPAL_SANDBOX_CLIENT_ID=your_sandbox_client_id
 *   PAYPAL_SANDBOX_CLIENT_SECRET=your_sandbox_client_secret
 */
class PayPalProcessor implements PaymentProcessorInterface
{
    public function __construct(private readonly bool $sandbox) {}

    // ─────────────────────────────────────────────────────────────────────────
    // PaymentProcessorInterface implementation
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Finalize / capture a PayPal payment after the client-side PayPal SDK has
     * approved the order.
     *
     * $payload carries:
     *   - ['order_id' => 'order_xxxx']
     */
    public function charge(float $amount, string $currency, array $payload): PaymentResult
    {
        $orderId = $payload['order_id'] ?? null;

        if (empty($orderId)) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'No PayPal order ID received.',
                processorName:     $this->getName(),
            );
        }

        try {
            $accessToken = $this->getAccessToken();
            $baseUrl = $this->getBaseUrl();

            // Capture the order
            $response = Http::withToken($accessToken)
                ->withHeaders([
                    'PayPal-Request-Id' => uniqid(),
                    'Content-Type' => 'application/json',
                ])
                ->post("$baseUrl/v2/checkout/orders/$orderId/capture", new \stdClass());

            if ($response->failed()) {
                // If it failed, let's verify if it was ALREADY captured (e.g. via double submit or webhook)
                $check = Http::withToken($accessToken)->get("$baseUrl/v2/checkout/orders/$orderId");
                if ($check->successful()) {
                    $orderData = $check->json();
                    if (($orderData['status'] ?? '') === 'COMPLETED') {
                        $captureId = $orderData['purchase_units'][0]['payments']['captures'][0]['id'] ?? $orderId;
                        return new PaymentResult(
                            success:           true,
                            authorizationCode: $captureId,
                            transactionId:     $orderId,
                            processorName:     $this->getName(),
                        );
                    }
                }

                $err = $response->json();
                $message = $err['message'] ?? $err['error_description'] ?? 'Capture failed.';
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    errorMessage:      "PayPal API Error: $message",
                    processorName:     $this->getName(),
                );
            }

            $data = $response->json();
            if (($data['status'] ?? '') !== 'COMPLETED') {
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    errorMessage:      'PayPal Order status: ' . ($data['status'] ?? 'unknown'),
                    processorName:     $this->getName(),
                );
            }

            $captureId = $data['purchase_units'][0]['payments']['captures'][0]['id'] ?? $orderId;

            return new PaymentResult(
                success:           true,
                authorizationCode: $captureId,
                transactionId:     $orderId,
                processorName:     $this->getName(),
            );

        } catch (\Throwable $e) {
            Log::error('PayPal capture error: ' . $e->getMessage());
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'PayPal verification failed: ' . $e->getMessage(),
                processorName:     $this->getName(),
            );
        }
    }

    /**
     * Create a PayPal order on the server side and return its ID.
     */
    public function createOrder(float $amount, string $currency): string
    {
        $accessToken = $this->getAccessToken();
        $baseUrl = $this->getBaseUrl();

        $response = Http::withToken($accessToken)
            ->withHeaders(['Content-Type' => 'application/json'])
            ->post("$baseUrl/v2/checkout/orders", [
                'intent' => 'CAPTURE',
                'purchase_units' => [
                    [
                        'amount' => [
                            'currency_code' => strtoupper($currency),
                            'value' => number_format($amount, 2, '.', ''),
                        ]
                    ]
                ]
            ]);

        if ($response->failed()) {
            $err = $response->json();
            $msg = $err['message'] ?? 'Could not create PayPal order.';
            throw new \RuntimeException($msg);
        }

        return $response->json()['id'];
    }

    public function getClientId(): string
    {
        return $this->sandbox
            ? config('services.paypal.sandbox_client_id') ?? env('PAYPAL_SANDBOX_CLIENT_ID', '')
            : config('services.paypal.client_id') ?? env('PAYPAL_CLIENT_ID', '');
    }

    private function getClientSecret(): string
    {
        return $this->sandbox
            ? config('services.paypal.sandbox_client_secret') ?? env('PAYPAL_SANDBOX_CLIENT_SECRET', '')
            : config('services.paypal.client_secret') ?? env('PAYPAL_CLIENT_SECRET', '');
    }

    private function getBaseUrl(): string
    {
        return $this->sandbox ? 'https://api-m.sandbox.paypal.com' : 'https://api-m.paypal.com';
    }

    private function getAccessToken(): string
    {
        $clientId = $this->getClientId();
        $clientSecret = $this->getClientSecret();
        $baseUrl = $this->getBaseUrl();

        if (empty($clientId) || empty($clientSecret)) {
            throw new \RuntimeException('PayPal credentials are not configured in the environment.');
        }

        $response = Http::withBasicAuth($clientId, $clientSecret)
            ->asForm()
            ->post("$baseUrl/v1/oauth2/token", [
                'grant_type' => 'client_credentials'
            ]);

        if ($response->failed()) {
            throw new \RuntimeException('Failed to authenticate with PayPal. Check client ID and secret.');
        }

        return $response->json()['access_token'];
    }

    public function isSandbox(): bool
    {
        return $this->sandbox;
    }

    public function getName(): string
    {
        return 'PayPal Payments';
    }
}
