<?php

namespace App\Services\Payments\Processors;

use App\Services\Payments\Contracts\PaymentProcessorInterface;
use App\Services\Payments\PaymentResult;

/**
 * StripeProcessor — built-in Stripe payment processor driver.
 *
 * This class is always available as a default processor (processor_id = 1).
 * It is PSR-4 autoloaded from app/Services/Payments/Processors/.
 *
 * CUSTOMISATION
 * ─────────────
 * Do NOT edit this file directly — it may be overwritten by platform updates.
 * To extend or override behaviour, create:
 *
 *   payment-processors/stripe/StripeProcessorExtension.php
 *
 * If that file exists, it is loaded automatically and used in place of this
 * class for processor_id = 1. See payment-processors/stripe/README.md for
 * a full extension template with examples.
 *
 * CREDENTIALS
 * ───────────
 * Add to .env (sandbox and/or production):
 *
 *   STRIPE_PUBLISHABLE_KEY=pk_live_xxxxxxxxxxxxxxxxxxxx
 *   STRIPE_SECRET_KEY=sk_live_xxxxxxxxxxxxxxxxxxxx
 *   STRIPE_SANDBOX_PUBLISHABLE_KEY=pk_test_xxxxxxxxxxxxxxxxxxxx
 *   STRIPE_SANDBOX_SECRET_KEY=sk_test_xxxxxxxxxxxxxxxxxxxx
 *   STRIPE_WEBHOOK_SECRET=whsec_xxxxxxxxxxxxxxxx
 *
 * SDK
 * ───
 *   composer require stripe/stripe-php
 */
class StripeProcessor implements PaymentProcessorInterface
{
    public function __construct(private readonly bool $sandbox) {}

    // ─────────────────────────────────────────────────────────────────────────
    // PaymentProcessorInterface implementation
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Record a Stripe payment after client-side Stripe.js confirmation.
     *
     * $payload = ['payment_intent_id' => 'pi_xxxx']
     */
    public function charge(float $amount, string $currency, array $payload): PaymentResult
    {
        $paymentIntentId = $payload['payment_intent_id'] ?? null;

        if (empty($paymentIntentId)) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'No Stripe PaymentIntent ID received.',
                processorName:     $this->getName(),
            );
        }

        // Support PaymentMethods / Subscriptions (used for direct subscription checkouts)
        if (str_starts_with($paymentIntentId, 'pm_') || str_starts_with($paymentIntentId, 'sub_')) {
            return new PaymentResult(
                success:           true,
                authorizationCode: $paymentIntentId,
                transactionId:     $paymentIntentId,
                processorName:     $this->getName(),
            );
        }

        // Support SetupIntents (used for trial subscriptions and setup-mode subscriptions)
        if (str_starts_with($paymentIntentId, 'seti_')) {
            try {
                $setupIntent = $this->client()->setupIntents->retrieve($paymentIntentId);

                if ($setupIntent->status !== 'succeeded') {
                    return new PaymentResult(
                        success:           false,
                        authorizationCode: '',
                        transactionId:     $setupIntent->id,
                        errorMessage:      'Setup not confirmed: ' . $setupIntent->status,
                        processorName:     $this->getName(),
                    );
                }

                return new PaymentResult(
                    success:           true,
                    authorizationCode: $setupIntent->id,
                    transactionId:     $setupIntent->id,
                    processorName:     $this->getName(),
                );
            } catch (\Stripe\Exception\ApiErrorException $e) {
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    errorMessage:      $e->getMessage(),
                    processorName:     $this->getName(),
                );
            }
        }

        try {
            $intent = $this->client()->paymentIntents->retrieve($paymentIntentId);

            if ($intent->status !== 'succeeded') {
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    transactionId:     $intent->id,
                    errorMessage:      'Payment not confirmed: ' . $intent->status,
                    processorName:     $this->getName(),
                );
            }

            $chargeId = $intent->latest_charge ?? $intent->id;

            return new PaymentResult(
                success:           true,
                authorizationCode: $chargeId,
                transactionId:     $intent->id,
                processorName:     $this->getName(),
            );

        } catch (\Stripe\Exception\ApiErrorException $e) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      $e->getMessage(),
                processorName:     $this->getName(),
            );
        }
    }

    public function isSandbox(): bool
    {
        return $this->sandbox;
    }

    public function getName(): string
    {
        return 'Stripe' . ($this->sandbox ? ' (Sandbox)' : '');
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Stripe-specific methods (used by OrderReview / checkout blade)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * The publishable key sent to the browser to initialise Stripe.js.
     */
    public function getPublishableKey(): string
    {
        return $this->sandbox
            ? (config('services.stripe.sandbox_publishable_key') ?? '')
            : (config('services.stripe.publishable_key') ?? '');
    }

    /**
     * Create a Stripe PaymentIntent and return its client_secret.
     * Called server-side in OrderReview::preparePayment().
     */
    public function createPaymentIntent(float $amount, string $currency = 'usd'): array
    {
        try {
            $intent = $this->client()->paymentIntents->create([
                'amount'                    => (int) round($amount * 100),
                'currency'                  => strtolower($currency),
                'automatic_payment_methods' => ['enabled' => true],
            ]);

            return [
                'client_secret'     => $intent->client_secret,
                'payment_intent_id' => $intent->id,
            ];

        } catch (\Stripe\Exception\ApiErrorException $e) {
            throw new \RuntimeException('Stripe PaymentIntent creation failed: ' . $e->getMessage(), 0, $e);
        }
    }

    /**
     * Create a Stripe Subscription for recurring billing.
     *
     * Two flows based on $meta:
     *
     * A) Existing price ID (pre-configured in Stripe Dashboard):
     *    $meta['stripe_price_id'] = 'price_xxx'
     *
     * B) On-the-fly product creation (create_new_stripe_product = 1):
     *    $meta['stripe_price_id'] is null/empty
     *    $meta['billing_interval']  = 'month' | 'year' | 'week'  (default: 'month')
     *    $meta['trial_days']        = int  (0 = no trial)
     *
     * Returns:
     *   [
     *     'client_secret'   => string,   // passed to Stripe.js to confirm
     *     'subscription_id' => string,
     *     'customer_id'     => string,   // persist on user record
     *     'is_subscription' => true,
     *     'trial_days'      => int,
     *   ]
     */
    public function createSubscription(float $amount, string $currency, array $meta = []): array
    {
        $client = $this->client();

        // ── 1. Resolve or create Stripe customer ─────────────────────────────
        $customerId = $meta['stripe_customer_id'] ?? null;
        if (empty($customerId)) {
            $customer   = $client->customers->create(array_filter([
                'email' => $meta['customer_email'] ?? null,
                'name'  => $meta['customer_name']  ?? null,
            ]));
            $customerId = $customer->id;
        }

        // ── 2. Resolve or create price ID ────────────────────────────────────
        $priceId = $meta['stripe_price_id'] ?? null;

        if (empty($priceId)) {
            $product  = $client->products->create([
                'name' => $meta['product_name'] ?? 'Store Subscription',
            ]);

            $interval = in_array($meta['billing_interval'] ?? 'month', ['month', 'year', 'week'])
                ? ($meta['billing_interval'] ?? 'month')
                : 'month';

            $price   = $client->prices->create([
                'unit_amount' => (int) round($amount * 100),
                'currency'    => strtolower($currency),
                'recurring'   => ['interval' => $interval],
                'product'     => $product->id,
            ]);

            $priceId = $price->id;
        }

        // ── 3. Build subscription params ─────────────────────────────────────
        $paymentMethodId = $meta['payment_method_id'] ?? null;
        if (!empty($paymentMethodId)) {
            try {
                $client->paymentMethods->attach($paymentMethodId, ['customer' => $customerId]);
            } catch (\Throwable) {}
            try {
                $client->customers->update($customerId, [
                    'invoice_settings' => ['default_payment_method' => $paymentMethodId],
                ]);
            } catch (\Throwable) {}
        }

        $params = [
            'customer' => $customerId,
            'items'    => [['price' => $priceId]],
            'expand'   => [
                'latest_invoice.payment_intent',
                'pending_setup_intent',
            ],
        ];

        if (!empty($paymentMethodId)) {
            $params['default_payment_method'] = $paymentMethodId;
        } else {
            $params['payment_behavior'] = 'default_incomplete';
            $params['payment_settings'] = [
                'save_default_payment_method' => 'on_subscription',
            ];
        }

        $trialDays = (int) ($meta['trial_days'] ?? 0);
        $trialPrice = (float) ($meta['trial_price'] ?? 0);

        if ($trialDays > 0) {
            $params['trial_period_days'] = $trialDays;

            // If a paid trial fee is configured, add it as an upfront invoice item
            if ($trialPrice > 0) {
                try {
                    $client->invoiceItems->create([
                        'customer'    => $customerId,
                        'amount'      => (int) round($trialPrice * 100),
                        'currency'    => $currency,
                        'description' => ($meta['trial_label'] ?? 'Trial Period Fee') . ' (' . $trialDays . ' days)',
                    ]);
                } catch (\Throwable $e) {
                    \Log::error('[StripeProcessor] Failed to create trial invoice item: ' . $e->getMessage());
                }
            }
        }

        // ── 4. Create subscription ───────────────────────────────────────────
        $subscription = $client->subscriptions->create($params);

        // Extract client_secret with multi-level fallback
        $clientSecret = null;

        // 4a. Check expanded latest_invoice -> payment_intent
        $latestInvoice = $subscription->latest_invoice ?? null;
        if (is_object($latestInvoice)) {
            $pi = $latestInvoice->payment_intent ?? null;
            if (is_object($pi) && !empty($pi->client_secret)) {
                $clientSecret = $pi->client_secret;
            } elseif (is_string($pi) && !empty($pi)) {
                try {
                    $retrievedPi = $client->paymentIntents->retrieve($pi);
                    $clientSecret = $retrievedPi->client_secret ?? null;
                } catch (\Throwable) {}
            } elseif (empty($pi) && !empty($latestInvoice->id)) {
                try {
                    $retrievedInv = $client->invoices->retrieve($latestInvoice->id, ['expand' => ['payment_intent']]);
                    if (is_object($retrievedInv->payment_intent)) {
                        $clientSecret = $retrievedInv->payment_intent->client_secret ?? null;
                    } elseif (is_string($retrievedInv->payment_intent)) {
                        $retrievedPi = $client->paymentIntents->retrieve($retrievedInv->payment_intent);
                        $clientSecret = $retrievedPi->client_secret ?? null;
                    }
                } catch (\Throwable) {}
            }
        } elseif (is_string($latestInvoice) && !empty($latestInvoice)) {
            try {
                $retrievedInv = $client->invoices->retrieve($latestInvoice, ['expand' => ['payment_intent']]);
                if (is_object($retrievedInv->payment_intent)) {
                    $clientSecret = $retrievedInv->payment_intent->client_secret ?? null;
                } elseif (is_string($retrievedInv->payment_intent)) {
                    $retrievedPi = $client->paymentIntents->retrieve($retrievedInv->payment_intent);
                    $clientSecret = $retrievedPi->client_secret ?? null;
                }
            } catch (\Throwable) {}
        }

        // 4b. Check pending_setup_intent (used for trial subscriptions or setup mode)
        if (empty($clientSecret)) {
            $pendingSetup = $subscription->pending_setup_intent ?? null;
            if (is_object($pendingSetup) && !empty($pendingSetup->client_secret)) {
                $clientSecret = $pendingSetup->client_secret;
            } elseif (is_string($pendingSetup) && !empty($pendingSetup)) {
                try {
                    $retrievedSi = $client->setupIntents->retrieve($pendingSetup);
                    $clientSecret = $retrievedSi->client_secret ?? null;
                } catch (\Throwable) {}
            }
        }

        // 4c. Check confirmation_secret if present on invoice
        if (empty($clientSecret) && isset($retrievedInv->confirmation_secret) && !empty($retrievedInv->confirmation_secret)) {
            $clientSecret = $retrievedInv->confirmation_secret;
        }

        // If subscription is active (e.g. paid on creation) and has no client_secret, fallback to subscription ID
        if (empty($clientSecret) && in_array($subscription->status, ['active', 'trialing'])) {
            $clientSecret = $subscription->id;
        }

        if (empty($clientSecret)) {
            throw new \RuntimeException(
                'Stripe subscription created but no client_secret returned. Subscription ID: ' . ($subscription->id ?? 'unknown')
            );
        }

        $paymentMethodTypes = null;
        if (is_object($latestInvoice) && is_object($latestInvoice->payment_intent ?? null)) {
            $paymentMethodTypes = $latestInvoice->payment_intent->payment_method_types ?? null;
        } elseif (isset($retrievedPi) && is_object($retrievedPi)) {
            $paymentMethodTypes = $retrievedPi->payment_method_types ?? null;
        }

        $piStatus = is_object($latestInvoice ?? null) && is_object($latestInvoice->payment_intent ?? null)
            ? ($latestInvoice->payment_intent->status ?? '')
            : '';

        $requiresAction = ($piStatus === 'requires_action' || $subscription->status === 'incomplete');

        return [
            'client_secret'        => $clientSecret,
            'subscription_id'      => $subscription->id,
            'customer_id'          => $customerId,
            'is_subscription'      => true,
            'trial_days'           => $trialDays,
            'status'               => $subscription->status,
            'requires_action'      => $requiresAction,
            'payment_method_types' => $paymentMethodTypes,
        ];
    }

    /**
     * Cancel a recurring Stripe subscription.
     *
     * Resolves sub_ IDs directly, or looks up active subscriptions by
     * PaymentMethod (pm_), PaymentIntent (pi_), or Customer (cus_) ID.
     *
     * @throws \Throwable
     */
    public function cancelSubscription(string $subscriptionId): bool
    {
        if (empty($subscriptionId)) {
            throw new \InvalidArgumentException('Stripe subscription ID cannot be empty.');
        }

        $client = $this->client();
        $targetSubId = $subscriptionId;

        // If a PaymentMethod ID (pm_...) was passed instead of sub_...
        if (str_starts_with($targetSubId, 'pm_')) {
            try {
                $pm = $client->paymentMethods->retrieve($targetSubId);
                if ($pm && !empty($pm->customer)) {
                    $subs = $client->subscriptions->all([
                        'customer' => $pm->customer,
                        'status'   => 'active',
                        'limit'    => 5,
                    ]);
                    if (!empty($subs->data)) {
                        $targetSubId = $subs->data[0]->id;
                    }
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning("[StripeProcessor] Could not resolve subscription from payment method {$targetSubId}: " . $e->getMessage());
            }
        }

        // If a PaymentIntent ID (pi_...) was passed instead of sub_...
        if (str_starts_with($targetSubId, 'pi_')) {
            try {
                $pi = $client->paymentIntents->retrieve($targetSubId);
                if ($pi && !empty($pi->customer)) {
                    $subs = $client->subscriptions->all([
                        'customer' => $pi->customer,
                        'status'   => 'active',
                        'limit'    => 5,
                    ]);
                    if (!empty($subs->data)) {
                        $targetSubId = $subs->data[0]->id;
                    }
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning("[StripeProcessor] Could not resolve subscription from payment intent {$targetSubId}: " . $e->getMessage());
            }
        }

        // If a Customer ID (cus_...) was passed
        if (str_starts_with($targetSubId, 'cus_')) {
            try {
                $subs = $client->subscriptions->all([
                    'customer' => $targetSubId,
                    'status'   => 'active',
                    'limit'    => 5,
                ]);
                if (!empty($subs->data)) {
                    $targetSubId = $subs->data[0]->id;
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning("[StripeProcessor] Could not resolve subscription from customer {$targetSubId}: " . $e->getMessage());
            }
        }

        try {
            $client->subscriptions->cancel($targetSubId);
            return true;
        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error("Stripe cancelSubscription failed for {$targetSubId} (input was {$subscriptionId}): " . $e->getMessage());
            throw $e;
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Protected helpers (overridable in extension class)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Returns a configured StripeClient.
     *
     * Made protected so extension classes can override the client
     * (e.g., to add custom HTTP options or a different SDK configuration).
     *
     * @throws \RuntimeException if SDK is missing or .env key is not set
     */
    protected function client(): \Stripe\StripeClient
    {
        if (!class_exists(\Stripe\StripeClient::class)) {
            throw new \RuntimeException(
                'The Stripe SDK is not installed. Run: composer require stripe/stripe-php'
            );
        }

        $secretKey = $this->sandbox
            ? (config('services.stripe.sandbox_secret_key') ?? '')
            : (config('services.stripe.secret_key') ?? '');

        if (empty($secretKey)) {
            throw new \RuntimeException(
                $this->sandbox
                    ? 'STRIPE_SANDBOX_SECRET_KEY is not set in .env'
                    : 'STRIPE_SECRET_KEY is not set in .env'
            );
        }

        return new \Stripe\StripeClient([
            'api_key'        => $secretKey,
            'stripe_version' => '2024-11-20.acacia',
        ]);
    }
}
