<?php

namespace App\Services\Payments\Processors;

use App\Services\Payments\Contracts\PaymentProcessorInterface;
use App\Services\Payments\PaymentResult;

/**
 * StripeProcessor — built-in Stripe payment processor driver.
 *
 * This class is always available as a default processor (processor_id = 1).
 * It is PSR-4 autoloaded from app/Services/Payments/Processors/.
 *
 * CUSTOMISATION
 * ─────────────
 * Do NOT edit this file directly — it may be overwritten by platform updates.
 * To extend or override behaviour, create:
 *
 *   payment-processors/stripe/StripeProcessorExtension.php
 *
 * If that file exists, it is loaded automatically and used in place of this
 * class for processor_id = 1. See payment-processors/stripe/README.md for
 * a full extension template with examples.
 *
 * CREDENTIALS
 * ───────────
 * Add to .env (sandbox and/or production):
 *
 *   STRIPE_PUBLISHABLE_KEY=pk_live_xxxxxxxxxxxxxxxxxxxx
 *   STRIPE_SECRET_KEY=sk_live_xxxxxxxxxxxxxxxxxxxx
 *   STRIPE_SANDBOX_PUBLISHABLE_KEY=pk_test_xxxxxxxxxxxxxxxxxxxx
 *   STRIPE_SANDBOX_SECRET_KEY=sk_test_xxxxxxxxxxxxxxxxxxxx
 *   STRIPE_WEBHOOK_SECRET=whsec_xxxxxxxxxxxxxxxx
 *
 * SDK
 * ───
 *   composer require stripe/stripe-php
 */
class StripeProcessor implements PaymentProcessorInterface
{
    public function __construct(private readonly bool $sandbox) {}

    // ─────────────────────────────────────────────────────────────────────────
    // PaymentProcessorInterface implementation
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Record a Stripe payment after client-side Stripe.js confirmation.
     *
     * $payload = ['payment_intent_id' => 'pi_xxxx']
     */
    public function charge(float $amount, string $currency, array $payload): PaymentResult
    {
        $paymentIntentId = $payload['payment_intent_id'] ?? null;

        if (empty($paymentIntentId)) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      'No Stripe PaymentIntent ID received.',
                processorName:     $this->getName(),
            );
        }

        try {
            $intent = $this->client()->paymentIntents->retrieve($paymentIntentId);

            if ($intent->status !== 'succeeded') {
                return new PaymentResult(
                    success:           false,
                    authorizationCode: '',
                    transactionId:     $intent->id,
                    errorMessage:      'Payment not confirmed: ' . $intent->status,
                    processorName:     $this->getName(),
                );
            }

            $chargeId = $intent->latest_charge ?? $intent->id;

            return new PaymentResult(
                success:           true,
                authorizationCode: $chargeId,
                transactionId:     $intent->id,
                processorName:     $this->getName(),
            );

        } catch (\Stripe\Exception\ApiErrorException $e) {
            return new PaymentResult(
                success:           false,
                authorizationCode: '',
                errorMessage:      $e->getMessage(),
                processorName:     $this->getName(),
            );
        }
    }

    public function isSandbox(): bool
    {
        return $this->sandbox;
    }

    public function getName(): string
    {
        return 'Stripe' . ($this->sandbox ? ' (Sandbox)' : '');
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Stripe-specific methods (used by OrderReview / checkout blade)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * The publishable key sent to the browser to initialise Stripe.js.
     */
    public function getPublishableKey(): string
    {
        return $this->sandbox
            ? (config('services.stripe.sandbox_publishable_key') ?? '')
            : (config('services.stripe.publishable_key') ?? '');
    }

    /**
     * Create a Stripe PaymentIntent and return its client_secret.
     * Called server-side in OrderReview::preparePayment().
     */
    public function createPaymentIntent(float $amount, string $currency = 'usd'): array
    {
        try {
            $intent = $this->client()->paymentIntents->create([
                'amount'                    => (int) round($amount * 100),
                'currency'                  => strtolower($currency),
                'automatic_payment_methods' => ['enabled' => true],
            ]);

            return [
                'client_secret'     => $intent->client_secret,
                'payment_intent_id' => $intent->id,
            ];

        } catch (\Stripe\Exception\ApiErrorException $e) {
            throw new \RuntimeException('Stripe PaymentIntent creation failed: ' . $e->getMessage(), 0, $e);
        }
    }

    /**
     * Create a Stripe Subscription for recurring billing.
     *
     * Two flows based on $meta:
     *
     * A) Existing price ID (pre-configured in Stripe Dashboard):
     *    $meta['stripe_price_id'] = 'price_xxx'
     *
     * B) On-the-fly product creation (create_new_stripe_product = 1):
     *    $meta['stripe_price_id'] is null/empty
     *    $meta['billing_interval']  = 'month' | 'year' | 'week'  (default: 'month')
     *    $meta['trial_days']        = int  (0 = no trial)
     *
     * Returns:
     *   [
     *     'client_secret'   => string,   // passed to Stripe.js to confirm
     *     'subscription_id' => string,
     *     'customer_id'     => string,   // persist on user record
     *     'is_subscription' => true,
     *     'trial_days'      => int,
     *   ]
     */
    public function createSubscription(float $amount, string $currency, array $meta = []): array
    {
        $client = $this->client();

        // ── 1. Resolve or create Stripe customer ─────────────────────────────
        $customerId = $meta['stripe_customer_id'] ?? null;
        if (empty($customerId)) {
            $customer   = $client->customers->create(array_filter([
                'email' => $meta['customer_email'] ?? null,
                'name'  => $meta['customer_name']  ?? null,
            ]));
            $customerId = $customer->id;
        }

        // ── 2. Resolve or create price ID ────────────────────────────────────
        $priceId = $meta['stripe_price_id'] ?? null;

        if (empty($priceId)) {
            $product  = $client->products->create([
                'name' => $meta['product_name'] ?? 'Store Subscription',
            ]);

            $interval = in_array($meta['billing_interval'] ?? 'month', ['month', 'year', 'week'])
                ? ($meta['billing_interval'] ?? 'month')
                : 'month';

            $price   = $client->prices->create([
                'unit_amount' => (int) round($amount * 100),
                'currency'    => strtolower($currency),
                'recurring'   => ['interval' => $interval],
                'product'     => $product->id,
            ]);

            $priceId = $price->id;
        }

        // ── 3. Build subscription params ─────────────────────────────────────
        $params = [
            'customer'         => $customerId,
            'items'            => [['price' => $priceId]],
            'payment_behavior' => 'default_incomplete',
            'expand'           => ['latest_invoice.payment_intent'],
        ];

        $trialDays = (int) ($meta['trial_days'] ?? 0);
        if ($trialDays > 0) {
            $params['trial_period_days'] = $trialDays;
        }

        // ── 4. Create subscription ───────────────────────────────────────────
        $subscription = $client->subscriptions->create($params);

        $clientSecret = $subscription->latest_invoice?->payment_intent?->client_secret ?? null;

        if (empty($clientSecret) && $trialDays === 0) {
            throw new \RuntimeException(
                'Stripe subscription created but no client_secret returned.'
            );
        }

        return [
            'client_secret'   => $clientSecret ?? '',
            'subscription_id' => $subscription->id,
            'customer_id'     => $customerId,
            'is_subscription' => true,
            'trial_days'      => $trialDays,
        ];
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Protected helpers (overridable in extension class)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Returns a configured StripeClient.
     *
     * Made protected so extension classes can override the client
     * (e.g., to add custom HTTP options or a different SDK configuration).
     *
     * @throws \RuntimeException if SDK is missing or .env key is not set
     */
    protected function client(): \Stripe\StripeClient
    {
        if (!class_exists(\Stripe\StripeClient::class)) {
            throw new \RuntimeException(
                'The Stripe SDK is not installed. Run: composer require stripe/stripe-php'
            );
        }

        $secretKey = $this->sandbox
            ? (config('services.stripe.sandbox_secret_key') ?? '')
            : (config('services.stripe.secret_key') ?? '');

        if (empty($secretKey)) {
            throw new \RuntimeException(
                $this->sandbox
                    ? 'STRIPE_SANDBOX_SECRET_KEY is not set in .env'
                    : 'STRIPE_SECRET_KEY is not set in .env'
            );
        }

        return new \Stripe\StripeClient($secretKey);
    }
}
