<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Discount extends Model
{
    protected $table = 'discounts';

    protected $fillable = [
        'discount_type_id',
        'value_type',
        'order_minimum',
        'order_maximum',
        'order_qty_min',
        'order_qty_max',
        'product_id',
        'name',
        'value',
        'code',
        'code_type',
        'times_redeemed',
        'get_x_free',
        'free_range1',
        'free_range2',
        'free_percent',
        'show_get_x_free',
        'show_get_x_text',
        'buy_x_get_y',
        'product_id_y',
        'product_y_percent',
        'start_date',
        'expiration_date',
        'is_active',
        'store_id',
        'brand_id',
        'brand_qty_min',
        'brand_qty_max',
        'brand_subtotal_min',
        'brand_subtotal_max',
        'category_id',
        'cat_qty_min',
        'cat_qty_max',
        'cat_subtotal_min',
        'cat_subtotal_max',
        'subcat_id',
        'subcat_qty_min',
        'subcat_qty_max',
        'subcat_subtotal_min',
        'subcat_subtotal_max',
        'style_id',
        'style_qty_min',
        'style_qty_max',
        'style_subtotal_min',
        'style_subtotal_max',
        'item_qty_min',
        'item_qty_max',
        'item_subtotal_min',
        'item_subtotal_max',
        'bogo_cart_text',
        'free_shipping',
        'wholesale_only',
        'order_weight_min',
        'order_weight_max'
    ];

    protected $casts = [
        'value_type' => 'integer',
        'order_minimum' => 'double',
        'order_maximum' => 'double',
        'order_qty_min' => 'integer',
        'order_qty_max' => 'integer',
        'product_id' => 'integer',
        'value' => 'double',
        'code_type' => 'integer',
        'times_redeemed' => 'integer',
        'get_x_free' => 'integer',
        'free_range1' => 'integer',
        'free_range2' => 'integer',
        'free_percent' => 'double',
        'show_get_x_free' => 'integer',
        'buy_x_get_y' => 'integer',
        'product_id_y' => 'integer',
        'product_y_percent' => 'double',
        'start_date' => 'datetime',
        'expiration_date' => 'datetime',
        'is_active' => 'integer',
        'store_id' => 'integer',
        'brand_id' => 'integer',
        'brand_qty_min' => 'integer',
        'brand_qty_max' => 'integer',
        'brand_subtotal_min' => 'double',
        'brand_subtotal_max' => 'double',
        'category_id' => 'integer',
        'cat_qty_min' => 'integer',
        'cat_qty_max' => 'integer',
        'cat_subtotal_min' => 'double',
        'cat_subtotal_max' => 'double',
        'subcat_id' => 'integer',
        'subcat_qty_min' => 'integer',
        'subcat_qty_max' => 'integer',
        'subcat_subtotal_min' => 'double',
        'subcat_subtotal_max' => 'double',
        'style_id' => 'integer',
        'style_qty_min' => 'integer',
        'style_qty_max' => 'integer',
        'style_subtotal_min' => 'double',
        'style_subtotal_max' => 'double',
        'item_qty_min' => 'integer',
        'item_qty_max' => 'integer',
        'item_subtotal_min' => 'double',
        'item_subtotal_max' => 'double',
        'free_shipping' => 'integer',
        'wholesale_only' => 'integer',
        'order_weight_min' => 'double',
        'order_weight_max' => 'double',
    ];

    public function discountType(): BelongsTo
    {
        return $this->belongsTo(DiscountType::class, 'discount_type_id');
    }
}
